# About the Contributors {-}

Matthew Bodie[`r icon::ai("orcid")`](https://orcid.org/0000-0001-9133-7685) is the Callis Family Professor of Law at Saint Louis University.

Alan Bogg is a Professor of Law at the [University of Bristol](http://www.bristol.ac.uk/law/people/alan-l-bogg/overview.html).

Elizabeth Brown is an Associate Professor, Law, Taxation, and Financial Planning, at Bentley University.

David Doorey is an Associate Professor of Work Law at [York University](https://profiles.laps.yorku.ca/profiles/ddoorey/).

Michael C. Duff is a Professor of Law at the [University of Wyoming](http://www.uwyo.edu/law/directory/mike-duff.html).

Michael D. Ford is a Professor of Law at the [University of Bristol](http://www.bristol.ac.uk/law/people/michael-d-ford/index.html).

Charlotte Garden is an Associate Professor of Law at [Seattle University](https://law.seattleu.edu/faculty/profiles/charlotte-garden).

Jeffrey M. Hirsch is the Geneva Yeargan Rand Distinguished Professor of Law at the University of North Carolina.

Anthony Forsyth[`r icon::ai("orcid")`](https://orcid.org/0000-0003-0790-8524) is a Professor in the Graduate School of Business and Law at RMIT University, Australia.

Ann C. Juliano is a Professor of Law at [Villanova University](https://www1.villanova.edu/villanova/law/academics/faculty/Facultyprofiles/AnnCJuliano.html).

César F. Rosado Marzán is a Professor of Law at the [University of Iowa](https://library.law.uiowa.edu/cesar-f-rosado-marzan).

Sachin S. Pandya[`r icon::ai("orcid")`](http://orcid.org/0000-0001-7387-1307) is a Professor of Law at the University of Connecticut.

Elizabeth Pendo is the Joseph J. Simeone Professor of Law at Saint Louis University.

Elizabeth Tippett is an Associate Professor of Law at the [University of Oregon](https://law.uoregon.edu/people/faculty/tippett).

Deborah Widiss[`r icon::ai("google-scholar")`](https://scholar.google.com/citations?user=lp6kuV0AAAAJ&hl=en) is a Professor of Law at Indiana University.

Jamillah Bowman Williams is an Associate Professor of Law at [Georgetown University](https://www.law.georgetown.edu/faculty/jamillah-bowman-williams/).

Ruqaiijah Yearby[`r icon::ai("orcid")`](https://orcid.org/0000-0002-2381-9401) is a Professor of Law at Saint Louis University.
