# (PART\*) Workplace Safety {-} 

# OSHA

_Sachin S. Pandya_, 2020-09-14

COVID-19 has highlighted the ways that law in the U.S. protects worker health and safety, as well as the gap between that law on paper and in action. Here, we'll cover some of the basics of the key federal workplace safety law -- the Occupational Safety and Health Act of 1970.

## Federal Law: OSHA {#oshafed}

On paper, the Occupational Safety and Health Act of 1970 (the OSH Act) provides for worker health and safety in three main ways.  

First, its so-called General Duty clause requires each employer to "furnish to each of his employees employment and a place of employment which are free from recognized hazards that are causing or are likely to cause death or serious physical harm to his employees." [29 U.S.C. § 654(a)(1)](https://www.govinfo.gov/content/pkg/USCODE-2018-title29/html/USCODE-2018-title29-chap15-sec654.htm). 

Second, the OSH Act requires employers to "comply with occupational safety and health standards promulgated under this Act." Id. § 654(a)(2). To date, however, there is no such standard for airborne infectious diseases. OSHA had been working on a new standard for airborne infectious disease to protect workers in hospitals and nursing homes, but in 2017 the Trump Administration removed that standard from the regulatory agenda [@Mann2020]. There are OSHA standards for using personal protective equipment (PPE) for protecting the eyes, face, lungs, and hands, see [29 C.F.R. §§ 1910.133](https://www.ecfr.gov/cgi-bin/text-idx?SID=3ac7f62b21b5133ec8509a5a298b0a51&mc=true&node=se29.5.1910_1133&rgn=div8), [1910.134](https://www.ecfr.gov/cgi-bin/text-idx?SID=3ac7f62b21b5133ec8509a5a298b0a51&mc=true&node=se29.5.1910_1134&rgn=div8), [1910.138](https://www.ecfr.gov/cgi-bin/text-idx?SID=3ac7f62b21b5133ec8509a5a298b0a51&mc=true&node=se29.5.1910_1138&rgn=div8), that might apply where workers need PPE to protect against COVID-19 exposure.

Third, the OSH Act contains an anti-retaliation provision. An employer may not fire or discriminate against an employee because that employee

>has filed any complaint or instituted or caused to be instituted any proceeding under or related to this chapter or has testified or is about to testify in any such proceeding or because of the exercise by such employee on behalf of himself or others of any right afforded by this chapter.

[29 U.S.C. § 660(c)(1)](https://www.govinfo.gov/content/pkg/USCODE-2018-title29/html/USCODE-2018-title29-chap15-sec660.htm).  

The phrase "any right afforded by this chapter" in this provision covers a broad range of employee actions, including asking OHSA for information or cooperating with OSHA inspectors. [29 C.F.R. § 1977.12(a)](https://www.ecfr.gov/cgi-bin/text-idx?SID=3ac7f62b21b5133ec8509a5a298b0a51&mc=true&node=se29.9.1977_112&rgn=div8). It typically does _not_ protect employees "refusing to perform normal job activities because of alleged safety or health hazards," [29 C.F.R. § 1977.12(b)(1)](https://www.ecfr.gov/cgi-bin/text-idx?SID=3ac7f62b21b5133ec8509a5a298b0a51&mc=true&node=se29.9.1977_112&rgn=div8), unless that hazard exposes the employee to a real risk of serious injury or death; the employee refuses in "good faith" to expose himself to it; the employee had already tried and failed to get the employer to correct the hazard; and the situation is so urgent that there isn't enough time "to eliminate the danger through resort to regular statutory enforcement channels," id. § 1977.12(b)(2).

There is, however, no private right to sue employers under the OSH Act. Instead, the Occupational Health and Safety Agency (OHSA) -- a federal government agency -- is the exclusive enforcer of the OSH Act's General Duty clause and of the safety standards issued under that Act, by way of inspections and civil penalties.  Similarly, if an employer retaliates against an employee, that employee must file a complaint with OSHA within 30 days. Thereafter, only OSHA may sue that employer for violating the OSH Act's anti-retaliation provision. [29 U.S.C. § 660(c)(2)](https://www.govinfo.gov/content/pkg/USCODE-2018-title29/html/USCODE-2018-title29-chap15-sec660.htm). If OSHA declines, the OSH Act provides no alternative path.

## OSHA Enforcement {#oshaenfr}

In April 2020, OSHA told its regional administrators that, because of COVID-related business closures, travel and group-size limits, and other restrictions, safety inspectors should judge whether an employer "made good faith efforts to comply with applicable OSHA standards" and if compliance wasn't possible, "to ensure that employees were not exposed to hazards from tasks, processes, or equipment for which they were not prepared or trained" [@OSHA_mem_april2020]. OSHA also published a guidance document to help employers implement engineering, administrative, and work practice controls and PPE to reduce COVID-19 exposure risk in the workplace, as part of an Infection Disease Preparedness and Response Plan [@OSHA_g2020].

Critics have complained about OSHA's enforcement efforts as unduly lax [@Scheiber2020; @Michaels2020]. From February through August 2020, OSHA received about 7,700 COVID-related complaints and about 1,000 COVID-related referrals (mostly from the health care industry); closed about 6,800 cases; but issued only two citations [@OSHA2020]. In issuing citations, OSHA has a short time window -- within "six months following the occurrence of any violation." [29 U.S.C. § 658(c)](https://www.govinfo.gov/content/pkg/USCODE-2018-title29/html/USCODE-2018-title29-chap15-sec658.htm).

In early September 2020, OHSA announced that it had cited five businesses for violating the OSH Act's General Duty clause, [29 U.S.C. § 654(a)(1)](https://www.govinfo.gov/content/pkg/USCODE-2018-title29/html/USCODE-2018-title29-chap15-sec654.htm), because each business had failed to sufficiently protect their workers from COVID-19 exposure [@OSHA_pr, releases dated 9-10, 9-11]. 

Among these citations, OSHA had cited the Smithfield meatpacking facility in Sioux Falls, South Dakota, for one "serious" violation of the General Duty Clause for failing to protect employees from COVID-19 exposure. At least 1,294 Smithfield workers had contracted COVID-19, 43 of them were hospitalized, and four of them had died as a result. OSHA proposed a penalty of \$13,494. [OSHA Citation and Notification of Penalty, Inspection No. 1472736 (Sept. 8, 2020)](https://big.assets.huffingtonpost.com/athena/files/2020/09/10/5f5a5589c5b62874bc19d98b.pdf). For details on the Smithfield case, see @Steinberg2020.

Although critics complained that OSHA's penalty against Smithfield was unduly low [@Kindy2020], in its press release, OSHA called that penalty "the maximum allowed by law" [@OSHA2020_0910_smith_pr]. OSHA was referring to section 17 of the OSH Act, which sets maximum civil penalty amounts for violating the OSH Act's General Duty clause or a particular occupational safety and health standard. Today, those amounts must be annually adjusted for inflation. For 2020, those penalty amounts were:

1. for an employer who "willfully or repeatedly" violates, \$134,037 maximum "for each violation"
2. for an employer cited for a "serious violation", \$13,494 maximum "for each such violation"
3. for an employer cited for a violation "specifically determined not to be of a serious nature, \$13,494 maximum "for each such violation"
4. for an employer who fails to correct a violation for which a citation has been issued, \$13,494 maximum "for each day during which such failure or violation continues".

[29 U.S.C. § 666](https://www.govinfo.gov/content/pkg/USCODE-2018-title29/html/USCODE-2018-title29-chap15-sec666.htm); [29 C.F.R. § 1903.15(d) (2020)](https://www.ecfr.gov/cgi-bin/text-idx?SID=b27c24ab9a81a61eac4f92ad63eb0e00&mc=true&node=se29.5.1903_115&rgn=div8).

Because they mostly apply to "each" employer violation, these penalty maximums in fact constrain OSHA depending on how easily OSHA can treat an employer's conduct as amounting to one violation or many, and as "willful" or not. For example, if an employer's conduct amounts to not one "serious" violation, but five separate "serious" violations, the maximum civil penalty is \$67,470 ($= 13494 \times 5$).  And if all five of those violations can count as "willful", then the maximum civil penalty jumps to \$670,185 ($= 134037 \times 5$).

For penalties for violating the General Duty clause, OSHA's ability to do this depends on what can count as a separate and distinct "violation" of the General Duty clause. Commenting on the Smithfield case, the former OSHA head in the Obama administration suggested that, in not treating Smithfield as having committed multiple willful violations, OSHA had deliberately imposed a far lower civil penalty that it could have [@Philpott2020].

In contrast, when OSHA writes an occupational safety standard, it can define what counts as a violation within the standard itself, and thereby "define the unit of prosecution" when it comes to imposing civil penalties. [National Association of Home Builders v. OSHA, 602 F.3d 464, 467 (D.C. Cir. 2010)](https://www.courtlistener.com/opinion/1992/nat-assn-of-home-builders-v-osha/). For example, for OSHA safety standards that require providing personal protective equipment (PPE) to employees for, among other things, protecting the eyes, face, lungs, and hands, the employer "must provide PPE to each employee required to use the PPE, and each failure to provide PPE to an employee may be considered a separate violation." [29 C.F.R. § 1910.9(a)](https://www.ecfr.gov/cgi-bin/text-idx?SID=3394fe091c7c2e109d0d1cec868295b2&mc=true&node=pt29.5.1910&rgn=div5#se29.5.1910_19).

## Emergency Temporary Standards {#oshaets}

Since March 2020, OSHA has refused to adopt an emergency temporary safety standard (ETS) for airborne infectious disease that would cover COVID-19 exposure in the workplace.

Although OSHA takes many years to promulgate safety standards, OSHA may also issue an "emergency temporary standard to take immediate effect" when published in the Federal Register if OSHA determines

>(A) that employees are exposed to grave danger from exposure to substances or agents determined to be toxic or physically harmful or from new hazards, and 
>(B) that such emergency standard is necessary to protect employees from such danger.

[29 U.S.C. § 655(c)(1)](https://www.govinfo.gov/content/pkg/USCODE-2018-title29/html/USCODE-2018-title29-chap15-sec655.htm). OSHA has not issued an ETS since 1983 [@Szymendera2020, appendix].

OSHA thus far refused to adopt an ETS that would cover COVID-19 exposure. And while a court may order OHSA to adopt an ETS in limited circumstances see 5 U.S.C. § 706(1), the U.S. Court of Appeals for the D.C. Circuit has thus far refused to order OSHA to issue an ETS:  

> The OSHA’s decision not to issue an ETS is entitled to considerable deference. In light of the unprecedented nature of the COVID-19 pandemic, as well as the regulatory tools that the OSHA has at its disposal to ensure that employers are maintaining hazard-free work environments, see 29 U.S.C. § 654(a), the OSHA reasonably determined that an ETS is not necessary at this time."

In re: AFL-CIO (D.C. Cir., June 11, 2020)(citation omitted). 

On similar grounds, that court denied a petition by the United Mine Workers union to the Mine Safety and Health Administration to use its powers to issue an ETS under the Federal Mine and Safety Act, [30 U.S.C. § 811(b)](https://www.govinfo.gov/content/pkg/USCODE-2018-title30/html/USCODE-2018-title30-chap22-subchapI-sec811.htm). That court held that it was reasonable for the agency to find that an ETS was not yet "necessary". [In re United Mine Workers, No. 20-1215, (D.C. Cir., July 16, 2020)](https://www.cadc.uscourts.gov/internet/orders.nsf/3587402FD4A1AEEB852585A700513EF3/$file/20-1215LDSD.pdf). In late July 2020, a coalition of unions petitioned the US Department of Transportation for a mandatory mask rule. [Letter for TTD to Chao, dated July 27, 2020](https://ttd.org/wp-content/uploads/2020/07/TTD-Petition-for-Rulemaking-to-DOT-7.27.20-1.pdf). That request is pending.

## State OSHA {#oshastate}

The OSH Act does permit States to enforce work safety under pre-approved plans, including issuing their own safety standards, provided the plan is no less effective than the OSH Act in protecting workers from work-related injuries, illnesses and deaths. Today, twenty-two states have OSHA approved plans, and six States have approved plans covering only state and local government workers [@OSHA_stpl]. 

These States can thereby issue safety standards on their own to cover their State. For example, California's work safety agency (Cal/OSHA) has a occupational safety standard for protecting against aerosol transmissible diseases in medical and some other workplaces. [Cal. Regs. tit. 8, $\S$ 5199](https://www.dir.ca.gov/title8/5199.html). 

In July 2020, Virginia's workplace safety agency issued an emergency temporary standard specifically for COVID-19 exposure. [§ 16 VAC 25-220](https://www.doli.virginia.gov/wp-content/uploads/2020/07/COVID-19-Emergency-Temporary-Standard-FOR-PUBLIC-DISTRIBUTION-FINAL-7.17.2020.pdf). For details, see @Szymendera2020 [pp. 10-15].

State safety agencies have varied in their efforts to reduce COVID-19 workplace exposure risk [e.g., @Zou2020].
