# Protecting the Health and Safety of Meat and Poultry Processing Workers {#meatpacking}

_Ruqaiijah Yearby_, 2020-09-29

This Chapter discusses how by failing to enforce health and safety standards, the government caused meat and poultry processing workers to be unnecessarily exposed to COVID-19 in the workplace. Moreover, the industry's political influence affected decisions that made matters worse, especially by securing from President Trump an  Executive Order invoking the Defense Production Act.  The U.S. Department of Agriculture (USDA) has brandished the authority delegated to it under that Order to keep open or re-open meat and poultry processing facilities despite inadequate COVID-19 safety guidelines to protect workers. 

## Failures to Enforce Health and Safety Protections 

The food and agriculture industry has the second highest percentage (21%) of essential workers in the US [@McNicholas2020].  Within that industry, meat and poultry processing businesses employ about 525,000 workers in 3,500 facilities nationwide [@Dyal2020]. To date, more than 43,000 meat and poultry processing workers have tested positive for COVID-19 and about 200 have died [@Douglas2020]. Racial and ethnic minorities, though 50% of meat and poultry processing workers, account for 87% of COVID-19 cases among those workers [@Waltenburg2020; @Fremstad2020].

Despite the Occupational Safety and Health Act's General Duty Clause, [29 U.S.C. $\S$  654(a)(1)](https://www.govinfo.gov/content/pkg/USCODE-2018-title29/html/USCODE-2018-title29-chap15-sec654.htm), and specific safety standards requiring employers to provide employees with personal protective equipment, e.g., [29 C.F.R. $\S$  1910.134](https://www.ecfr.gov/cgi-bin/text-idx?SID=3ac7f62b21b5133ec8509a5a298b0a51&mc=true&node=se29.5.1910_1134&rgn=div8), the Occupational Safety and Health Administration (OSHA) has not adequately enforced these laws to protect worker health and safety. OHSA has also refused to issue an emergency temporary standard to address COVID-19 spread in the workplace.  To date, OSHA has only issued two fines for meat and poultry processing plants with COVID-19 outbreaks. OSHA fined the Smithfield plant in Sioux Falls, South Dakota \$13,494 after 1,294 employees tested positive, 43 were hospitalized and 4 died of COVID-19. OSHA also fined the JBS plant in Greeley, Colorado \$15,615. The Greeley JBS plant was responsible for nearly two-thirds of all Colorado COVID-19 cases [@Bradbury2020]. In 2019, Smithfield and JBS made \$14 billion and \$51.7 billion in net revenue, respectively [@Kindy2020]. 

On April 26, 2020, OSHA and the Centers for Disease Control and Prevention (CDC) issued a joint interim guidance for meat and poultry processing workers and employers [@CDC2020_meat]. The guidance recommended creating a COVID-19 assessment and control plan, which includes providing PPE and implementing social distancing. The guidance also stated that employers should "work with the appropriate state and local public health officials and occupational safety and health professionals," to develop plans for operating and addressing COVID-19 outbreaks. The guidance was later updated [@CDC2020_meat2]. Yet, there are many serious problems with the guidance.  

First, the guidance is not mandatory. Thus, some OSHA officials referred complaints to local health departments or stated that all they can do is "contact an employer and send an advisory letter outlining the recommended protective measures" [@Perez2020].

Second, the guidance did not recommend testing all workers after identification of an infected worker, even though such testing reduces the spread of COVID-19. For example, after nearly two-dozen workers were hospitalized, Tyson Foods tested all its workers and found 1,000 workers who tested positive for COVID-19, including many who did not show any symptoms. Had Tyson not tested all its workers, Tyson's asymptomatic workers would have continued to spread the disease. Since then, Tyson has tested almost every worker at its 20 facilities, which arguably slowed COVID-19's spread throughout its facilities [@Charles2020].

Third, the CDC/OSHA guidance was issued on April 26, long after severe industry outbreaks [@Yearby2020; @Grant2020]. For example, about a month earlier, on March 30, the federal government knew that the Canadian meat processing plant Olymel had to shut down because of COVID-19 infections  [@OSEC2020, 274-275]. 

Fourth, the guidance alone does not suffice, in part because once meat processing businesses learned of COVID-19 infections among their workers, they delayed closing plants with those workers.  To illustrate, consider the Smithfield plant in Sioux Falls, South Dakota. There, the first case of COVID-19 was detected on March 24, 2020. The plant, however, did not halt production until April 14. By that point, there were 735 COVID-19 infections at that plant -- the largest COIVD-19 hotspot at the time [@Sternlicht2020; @Grant2020; @Jankowicz2020]. 

The South Dakota Department of Health and the CDC completed an inspection of the facility on April 22 [@Grant2020]. Although the CDC noted in its report that its recommendations were discretionary, Smithfield continuously emailed the USDA to use the CDC's findings as support for re-opening the plant even as employee test results were still pending, an OSHA investigation was being conducted, and the South Dakota Governor was trying to get Smithfield to comply with state health and safety laws [@OSEC2020, 125-126, 175-178, 234-237, 307-308, 321-322]. On May 6, the USDA Undersecretary for Food Safety told Smithfield CEO Ken Sullivan that it expected the Sioux Falls plant to be reopened "immediately." Email from Brashears to Sullivan, May 6, 2020, in @OSEC2020, pp. 10-11. The facility in fact did re-open on May 6, and COVID-19 infections continued to spread throughout the plant until June 16 [@OSHAsmithcitation, 6]. 

Finally, although State OSHA agencies could have stepped in to fill OSHA's enforcement gap, key States have not done so.  For example, in mid-April 2020, 18.2% of Iowa meat and poultry processing plant workers were infected with COVID-19, the highest percentage of these workers infected by COVID-19 nationwide [@Dyal2020]. In fact, at one point in April not only were 90 percent of all COVID-19 cases in Waterloo, Iowa (Black Hawk County) tied to the meat processing plant there, but Black Hawk County also had the most COVID-19 cases in Iowa [@Eller2020]. But Iowa, a State with an OSHA approved plan, twice declined assistance from the CDC to address these COVID-19 outbreaks. By mid-May, Iowa still had the highest percentage of COVID-infected meat and poultry processing workers nationwide, with 1,784 meat processing plant workers being infected [@Kauffman2020]. Yet, neither Iowa nor OSHA has cited any of these facilities for workplace safety violations. In September, Iowa's OSHA agency fined the Iowa Premium Beef Plant -- where 338 out of 850 workers tested positive for the virus -- \$957 for a recordkeeping violation [@Foley2020].

## Executive Order 13917 and its Impact

Throughout the pandemic, the meat and poultry industry --  including trade associations like the Meat Institute, the National Chicken Council, and the North American Meat Institute (NAMI) -- lobbied the USDA to preserve business profits at the cost of worker safety. This effort resulted in President Trump's Executive Order 13917, issued on April 28, which the USDA then invoked to keep meat and poultry processing plants open.

In mid-March, industry actors lobbied USDA and the White House to have meat and poultry processing facilities added to the Department of Homeland Security's advisory list of "essential critical infrastructure workers" that States should exempt from stay-at-home orders [@OSEC2020, 36-39, 127-130, 163-164, 195-213, 216-218, 304-305]. The first version of Homeland Security's advisory list of such essential workers, dated March 19, expressly included those employed in "meat processing . . . facilities; livestock, poultry, seafood slaughter facilities." [@DHS2020, 4].  

Around the same time, the industry was also asking the USDA for help in securing masks, hand sanitizer, and cleaning materials [@OSEC2020, 30-34, 172-174]. On March 17, a food trade association asked USDA for "clear guidance from CDC or some authoritative USG public health office" about what to do if a food manufacturing facility had a positive COVID-19 case [@OSEC2020, 336]. By March 23, the food associations had issued guidance on what to do if an employee or customer tested positive for COVID-19, which included cleaning procedures, making an OSHA report, contacting state OSHA authorities, following the guidance from health officials, and informing employees of a potential exposure [@OSEC2020, 96-102]. 

For her part, USDA Undersecretary for Food Safety Mindy Brashears emphasized to NAMI that while USDA was working with the FDA to develop guidelines for social distancing in food plants, USDA would defer to local public health authorities: 

> In the absence of any illness, I suggest utilizing our guidelines to ask the health department to follow our federal recommendations for this situation. On the call Frank and I had with the local health authorities, we asked them to follow the guidance we have put out. However, I want to emphasize that the jurisdiction of health issues will be left to the local health departments. The requirements might change in areas of increased illness and/or if there is a confirmed illness in the processing facility. If there are illnesses they may require more stringent social distancing recommendations and/or quarantines. _We will rely on them to make the best decisions based on public health._ 

Email from Brashears to Potts, March 26, 2020 [@OSEC2020, 252-253, emphasis added].

By April, however, the meat and poultry industry had turned to President Trump for help in keeping plants open, despite rising COVID-19 infections among their workers. [@OSEC2020, 122-124, 359-361]. On April 21, NAMI's President emailed the USDA a draft Executive Order to the President to use to keep food processing, production, and supply companies open [@OSEC2020, 354-356].  

On April 28, two days after OSHA and the CDC issued their April 26 interim guidance, President Trump issued Executive Order 13917 [@EO13917]. The Order's text included language from the draft order sent by industry, such as the risk of meat shortages and the need to keep open meat and poultry processing facilities. In the Order, after referring to the President's powers granted by section 101 of the Defense Production Act of 1950, [50 U.S.C. $\S$ 4511](https://www.govinfo.gov/content/pkg/USCODE-2018-title50/html/USCODE-2018-title50-chap55-subchapI-sec4511.htm), the President delegated authority to the Secretary of Agriculture to 

>determine the proper nationwide priorities and allocation of all the materials, services, and facilities necessary to ensure the continued supply of meat and poultry, consistent with the guidance for the operations of meat and poultry processing facilities jointly issued by the CDC and OSHA 

[@EO13917, 261314].

In so doing, this Order relied on section 101(a) of the Defense Production Act, which authorizes the President in part to "allocate materials, services, and facilities in such manner, upon such conditions, and to such extent as he shall deem necessary or appropriate to promote the national defense." [50 U.S.C. $\S$ 4511(a)(2)](https://www.govinfo.gov/content/pkg/USCODE-2018-title50/html/USCODE-2018-title50-chap55-subchapI-sec4511.htm). The President, however, may not use this authority to control material distributed in the civilian market

>unless the President finds (1) that such material is a scarce and critical material essential to the national defense, and (2) that the requirements of the national defense for such material cannot otherwise be met without creating a significant dislocation of the normal distribution of such material in the civilian market to such a degree as to create appreciable hardship. 

[50 U.S.C. $\S$ 4511(b)](https://www.govinfo.gov/content/pkg/USCODE-2018-title50/html/USCODE-2018-title50-chap55-subchapI-sec4511.htm). For background on the Defense Production Act, see @Cecire2020.

The Executive Order has two puzzling features.

First, although President Trump declared that meat and poultry protein is a "scare and critical material essential to the national defense," [@EO13917, 26313], data on meat exports suggested little scarcity or appreciable hardship that section 101(b) of the Act requires. In April 2020, total pork exports to mainland China reached their highest monthly total in 20 years [@Corkery2020]. As of July 2, beef (5%) and poultry (14%) production were up compared to a year ago [@Bunge2020]. 

Second, the Order pointed to "recent actions in some States have led to the complete closure of some large processing facilities," and then argued that those actions "may differ from or be inconsistent with" the OSHA/CDC interim guidance for meat and poultry processing plants [@EO13917, 261313]. In fact, that guidance does not discuss what to do once multiple workers are infected within a workplace -- a serious failing of that guidance.  

Despite these puzzling features, the USDA thereafter invoked this Executive Order to keep open and re-open meat and poultry processing plants with COVID-19 outbreaks even if state and local health departments were trying to close facilities to slow the spread of COVID-19 [@OSEC2020, 10-12, 119, 256-258, 312-316, 346-347]. Indeed, just one day after the Executive Order was issued, the USDA was already receiving requests to overrule health department decisions to require testing of employees working at a facility with a COVID-19 outbreak because the positive results would force meat and poultry plants to close [@OSEC2020, 214-215]. 

About a week later, by letter, dated May 5, 2020, Agriculture Secretary Sonny Perdue invoked his delegated authority under the Defense Production Act to "exhort" meat and poultry processors to resume normal operations after complying with the April 26 CDC/OSHA guidance:

> Plants should resume operations as soon as they are able after implementing the CDC/OSHA guidance for the protection of workers. . . . Again, I exhort you to do this; further action under the Executive Order and the Defense Production Act is under consideration and will be taken if necessary.

[@Perdue2020]. This letter did not mention the need for testing, the State's public health power to order testing, or any intent to defer to State and local public health departments to make the best decisions based on public health.

After the USDA letter, meat and poultry trade associations continued to ask the USDA to help it stop state and local health departments who wanted them to close facilities due to COVID-19 outbreaks, require all employees be tested, and implement 6ft physical distancing. For example, the USDA intervened to get the Smithfield Kane County, Illinois meat processing plant back open that had closed because of a COVID-19 outbreak [@OSEC2020, 119, 256-258, 312-316, 346-347]. 

Since the Executive Order, COVID-19 infections and deaths in meat and poultry processing facilities have skyrocketed. In the one-month since the Order was issued, the number of COVID-19 infections more than tripled and the number of deaths quadrupled. Specifically, there were 16,233 confirmed cases of COVID-19 infections for meat and poultry processing workers and 86 COVD-19 related deaths in 239 facilities. Of the 9,919 (61%) cases with racial and ethnic data, 56% of COVID-19 cases occurred in Latinos, 19% occurred in non-Hispanic Black, 13% in non-Hispanic whites, and 12% in Asians. Yet, the actual numbers of COVID-19 infections and deaths for meat and poultry processing workers are probably higher because only 23 states submitted data and "only facilities with at least one laboratory-confirmed case of COVID-19 among workers were included" [@Waltenburg2020].
