# Causation for Workers' Compensation

_Michael C. Duff_, 2020-09-06

Workers compensation does not automatically cover the disability from a worker's COVID-19 infection. Rather, workers' compensation law requires proving causation, i.e., the infected employee's work increased the risk of contracting COVID-19, and therefore the employee's COVID-19 was a risk related to their employment. Some States have responded by adopting, for some kinds of workers, COVID-19 workers' compensation presumptions.

Workers' compensation is a state-based employee disability benefit system that has been in place in the United States since the early 20th century [@Witt2004; @Fishback2000]. Under workers compensation law, employees (or their familial successors) may not sue their employers in a "tort" lawsuit for money damages when suffering a work-related disability or death. In exchange, employees receive statutory benefits that are usually less generous -- about two-thirds of pre-disability weekly wages and payment of medical costs related to the disability [@Larson2020, chap. 80-86]. However, these benefits are, in theory, easier to get, because employees need not prove their employers were at fault and cannot be defeated by tort law defenses. 
					
## The Causation Requirement

Even though workers' compensation is "no fault," employees must still prove that their work caused disability for which compensation is sought. Though workers' compensation causation standards vary by State, they typically require the injured employee -- here, by contracting COVID-19 -- to prove that the employee's work increased the risk of contracting COVID-19 in order to show that the employee's risk of contracting COVID-19 was an "employment" risk. If I contract COVID-19, was I exposed to the coronavirus by a risk created by my job? Or was I exposed to the coronavirus by a risk created by, for example, stopping at the gas station on my way to work? Put another way, was my risk of contracting COVID-19 was any greater than the general public's risk of contracting the disease? [@Larson2020, § 3.03]. Behind this causation requirement is the policy that workers' compensation law should not require employers the absolute insurers of their employees' safety. [Fairhope Health and Rehab., 175 So.3d 622, 628 (Ala. 2015)](https://www.casemine.com/judgement/us/5ca1e548342cca16c797bd2f).

In some situations, causation will be easier to prove. For example, employees in "congregate" (high density) work settings are more likely to contract COVID-19 [@Waltenburg2020; @Wallace2020; @Steinberg2020]. A meatpacking employee working in a congregate workplace may be better able to prove that work probably caused the employee's COVID-19 than an employee working in a low density workplace. The meatpacking employee might also have been exposed to coronavirus at the local gas station, of course. But if the employee has been working long hours, and if the employee's spouse has been performing outside-the-household tasks while cautiously avoiding the coronavirus, a workers' compensation agency may be willing to find probable causation. Many workplaces may not so clearly exceed the general public's background risk of being exposed to the coronavirus. Employees in lower-risk workplaces will have a more difficult time proving causation. 

Further complicating causation is that some states categorically exclude infectious diseases or "ordinary diseases of life" from workers' compensation coverage. The policy behind such exclusions is probably that these types of diseases necessarily do not relate to employment risks. Thus if an employee contracts tuberculosis (an infectious disease) some states would categorically deny workers' compensation coverage for any resulting disability, even if the employee could prove contraction of tuberculosis at work. Some states (but not most) achieve non-coverage of such diseases by requiring they be causally linked to an identifiable workplace "accident". States following this approach generally required proof of an accident for any work-related disability. [Masterson v. Rutland Hosp., 129 Vt. 91 (1970)](https://www.casemine.com/judgement/us/5914986badd7b0493460403b). Because contraction of infectious diseases usually occurs over time rather than in a one-time accident disease claims were often disqualified on this basis [@Larson2020, § 5.05]. Some states more directly and explicitly exclude from workers' compensation coverage "ordinary diseases of life," even when work worsens such ordinary diseases. E.g, [Bunney v. Industrial Commission, 75 Ill. 2d 413 (1979)](https://www.casemine.com/judgement/us/59149374add7b049345aa7a2). Unsurprisingly, states vary as to what counts as an "ordinary" disease [@Larson2020, § 52.03[3]].   

In some ways, COVID-19 resembles occupational diseases, which workers' compensation law usually treats differently than "ordinary" or infectious diseases. Occupational diseases are those that have been empirically or statutorily associated with certain kinds of work. [@Larson2020, § 52.03]. Every State covers workers sustaining occupational diseases caused by work, though standards of causation vary and proving causation is often hard to do [@Larson2020, § 52.03[2]]. Consider, for example, a coal miner who daily goes to work and is exposed to coal dust. If he develops black-lung (pneumoconiosis), coal dust exposure may have caused the disease, because working in a coal mine increases the risk of contracting black lung. If he also smokes cigarettes, however, his smoking may also be a cause of his condition. The problem in these kinds of cases -- how to separate multiple possible causes -- centers on medical causation and evidence frequently conflicts. If employees bear the burden of proof in such cases, they are less likely to win on their workers compensation claims.

From its earliest history, workers' compensation has addressed the problem of occupational disease. For example, the British Workmen's Compensation Act of 1906, implicitly recognized that placing the burden of proof on employees in occupational disease claims would have the effect of routinely defeating claims, undermining the remedial purpose of the law. To prevent that outcome, the 1906 Act set up a statutory list of diseases (e.g., anthrax, lead poisoning, hookworm disease) with a statutory presumption.  Where a worker had been employed continuously for a designated period of time in a specific work process (e.g., handling wool, using lead, mining), and thereafter developed one of the listed diseases, the disease was presumed to have arisen out of employment. [Workmen's Compensation Act, 1906, 6 Edw. VII, c. 58, § 8](https://iiif.lib.harvard.edu/manifests/view/drs:6093232$11i) [@Hennock2007, 115; @Duff2019]. Such occupational disease presumptions later appeared in some early American workers' compensation statutes during the 1910s. By 1954, all but two states covered occupational diseases in some fashion.

Is COVID-19 categorically more like an occupational disease (typically covered) or infectious or ordinary diseases (typically not covered)? In high-risk workplaces, COVID-19 is similar to an occupational disease, because employee risk of contracting it at work is higher than the general public's infection risk. This seems especially true during periods of lockdown when state-designated essential workers -- unable to work remotely -- are being exposed to coronavirus, while the general public and employees working from home are not being similarly exposed. 

## Workers' Compensation Presumptions

Some states have created COVID-19 workers' compensation presumptions that are structured similarly to occupational disease presumptions. The COVID-19 presumptions typically make it easier for certain "essential workers" to prove their workers' compensation claims (Table 1). 

```{r wc_presumptions, message=FALSE, warning=FALSE, echo=FALSE}

data_load_path <- here::here("data","wc_presumptions_2020-08-01.csv")
#data_load_path <- "wc_presumptions_2020-08-01.csv"
d <- readr::read_csv(data_load_path)
d$source <- paste0("<a href='",d$source_url,"'target='_blank'>",d$source,"</a>")

library(dplyr)

d2 <- d %>%
  select(state, source, date, type, workers_covered, date_expired)

library(DT)

datatable(d2, escape=FALSE) %>% 
      formatStyle(columns = 1:5, `font-size` = '11px')

#knitr::kable(d2)


```
In general, if employees qualify for the presumption and are reliably diagnosed as having contracted COVID-19, the burden of proof on causation shifts from the employee to the employer (or insurance carrier). Then, the employer must prove that COVID-19 was _not_ caused by employment. E.g., [Minn. Stat. § 176.011(15)(f)](https://www.revisor.mn.gov/bills/text.php?number=HF4537&type=bill&version=0&session=ls91&session_year=2020&session_number=0). It can be as hard for employers to disprove causation as it is for employees to prove it. E.g., [Cadiz v. QSI, Inc., 2020 Haw. LEXIS 200 (June 30, 2020)](https://www.casemine.com/judgement/us/59145906add7b049341c329a).

Some insurance industry advocates deride the COVID-19 presumptions as potentially financially ruinous [e.g., @Langham2020]. In apparent response, California has decided not to include COVID-19 claims in employer experience rating [@insj2020]. This is like an insurer who, despite a motorist's car accident, does not increase that motorist's insurance premium, because of extraordinary circumstances. Such cost concerns are premature. COVID-19 claims costs will likely increase because of workers' compensation presumptions. But claims costs also likely decreased when state economies were or are locked down, because of the resulting employee inactivity. A leading insurance rate setting organization has stated that it cannot calculate aggregate insurance costs, other than through hypothetical scenarios, until later this year [@NCCI2020]. Furthermore, costs to employers and insurers aside, COVID-19 presumptions can be justified as a way to avoid employee financial ruin. 
	
More importantly, the COVID-19 presumptions are neither an unusual or novel. As discussed above, workers' compensation occupational disease presumptions have existed since the early 20th century. The federal black lung program contains five separate black lung/pneumoconiosis causation presumptions [@Szymendera2019, 6-7]. Disease causation presumptions also exist in the Energy Employees Occupational Illness Compensation Program for Department of Energy employees and others diagnosed with certain radiogenic cancers after working at a covered Department of Energy or atomic weapons facility during specific time periods [@Szymendera2020, 4]. Moreover, most states have adopted worker compensation presumptions for first responders with certain kinds of likely-work-related cancers [@FRC2020]. Whatever the expense of workers' compensation COVID-19 claims, it is unlikely to exceed the expense of first-responder cancer claims.

This provokes a different kind of fairness discussion. First responders are predominantly male and white. Police officers are 71% white; 96% of firefighters are men, and 82% are white [@Keating2020; @NFPA2020; @Bendersky2018]. And they earn relatively high median annual wages -- about \$50,000 for firefighters and \$63,000 for police officers [@BLS2020a; @BLS2020b]. By comparison, other COVID-19 essential workers, such as nursing home employees, home healthcare workers, and meat processing industry employees, tend to be paid less and be women of color [@Wiley2020, 21-22]. It is hard to justify first-responder disease presumptions while balking at payment of less expensive claims filed by lower-paid and disadvantaged groups during a pandemic. Both groups deserve protection if their diseases are likely caused by work, unless insurance carriers and employers can prove otherwise in a particular case. If we have a fairness discussion, it should be a complete one.

