# Workers' Compensation Exclusivity {#wc_exclusivity}

_Michael C. Duff_, 2020-12-10

Although workers' compensation is typically the exclusive remedy for work-related injuries, workers infected by COVID-19 or their families have brought tort claims for wrongful death and for public nuisance against employers. This commentary discusses how workers' compensation exclusivity operates, and why it is likely to preclude these COVID-19 lawsuits.

In the United States, workers' compensation law makes workers' compensation benefits an employee's exclusive remedy against his or her employer for negligently caused workplace death, injury, or disease. Thus, while customers or unaffiliated individuals may sue a company for negligent conduct, its own employees may not. This exclusivity rule is part of the early 20th century "Grand Bargain" between business and labor: Injured workers gave up their rights to sue employers under tort law in exchange for benefits set by statute that are easier to get [@Fishback2000, 105-110]. Today, all States except Texas and Wyoming require employers to participate in workers' compensation [@NASI2019, 6]. The courts vigorously enforce workers' compensation law's exclusivity principle [@MWC2020, $\S$ 102:1]. Courts will dismiss negligence lawsuits for work-related injury or death filed by employees against their employers [@Larson2020, $\S$ 100.01]. Courts also dismiss wrongful death lawsuits filed by eligible surviving family members of employees injured or killed by work. E.g., [Karhoff v. National Mills, 851 P.2d 1021 (Kan. App. 1993)](https://casetext.com/case/karhoff-v-national-mills-inc).

## Suing Despite Exclusivity

Despite workers' compensation exclusivity, injured workers still try to bring tort or other claims for work-related injuries, particularly if workers' compensation's statutory benefits are low, or because the workers compensation system does not provide any way to quickly force an employer to act to reduce workplace hazards.
	
First, because workers' compensation benefits are extremely limited, claimants try to escape the system by bringing negligence or wrongful death lawsuits. The workers' compensation system is a good bargain for injured employees who are eligible for workers' compensation benefits but would likely have lost negligence lawsuits against their employers under the traditional tort system. Injury, disease, or death "arising out of and in the course of" employment are broadly compensable irrespective of fault. Those benefits consist of a substantial percentage of pre-injury wages (indemnity benefits), and payment of all medical expenses related to work injuries (medical benefits). Totally disabled employees receive about two-thirds of their preinjury wages that are normally capped at a state's average weekly wage. Partially disabled employees receive less depending on the severity of a disability and on a given state's method of benefit calculation [@Larson2020, $\S$ 80.05]. Increasingly under the current system, indemnity benefits expire before disability has ended [@Spieler2012]. Eligible family members usually receive burial expenses and a portion of the indemnity benefits a deceased employee would have received had the employee survived [@Larson2020, $\S\S$ 98.02, 98.07]. 

Given such statutory benefits, workers' compensation exclusivity disadvantages claimants who under the traditional tort system would likely have won negligence lawsuits, and thus could have received more generous tort damages, i.e., full recovery for lost wages and medical expenses, damages for pain and suffering, and perhaps punitive damages [@Dobbs2017, 833-835]. But employees may be unable to accurately estimate the strength of their (hypothetical) negligence case and many -- especially those with serious injuries or diseases -- may prefer to avoid workers' compensation and be frustrated by exclusivity.

Second, exclusivity means that claimants cannot get injunctive relief or some other remedy to force employers to promptly reduce dangerous workplace hazards. By definition, workers' compensation provides only money as a remedy for injuries that have already occurred. Government worker safety agencies, not the workers' compensation system, are primarily charged with the role of quickly finding and forcing fixes of inadequate safety practices in the short term. This is why, for example, Congress gave the Occupational Safety and Health Administration (OSHA) the power to impose emergency workplace safety standards. [29 U.S.C. $\S$ 655(c)(1)](https://www.govinfo.gov/content/pkg/USCODE-2018-title29/html/USCODE-2018-title29-chap15-sec655.htm). When OSHA fails to exercise such power for COVID-19 workplace risk [@Scheiber2020], a State's workers' compensation system, because of its structure, cannot play that role.

## Exclusivity and Wrongful Death Suits

During the pandemic, the family of workers killed in dangerous workplaces (like meatpacking plants) have filed wrongful death lawsuits [@Adamy2020]. In a wrongful death lawsuit, designated family members pursue tort claims in cases where the defendant caused the death of another family member. E.g., [Mo. Rev. Stat. $\S$ 537.080]( https://revisor.mo.gov/main/OneSection.aspx?section=537.080). But for reasons discussed plaintiffs in these circumstances usually cannot prevail because of exclusivity. 

Why might they nevertheless bring wrongful death actions? Plaintiffs may be seeking to characterize employers' alleged conduct -- exposing employees to obvious risks of COVID-19 infection, for example -- as "intentional." About forty States do not apply exclusivity to "intentional" conduct either expressly by statute or by judicial interpretation [@Larson2020, $\S$ 103.01, nn. 5-6].  It will be hard, however, to prove that an employer's COVID-19-related misconduct was intentional. A leading commentator notes:

>Even if the alleged conduct goes beyond aggravated negligence, and includes such elements as knowingly permitting a hazardous work condition to exist, knowingly ordering employees to perform an extremely dangerous job, wilfully failing to furnish a safe place to work . . . wilfully violating a safety statute, failing to protect employees from crime, refusing to respond to an employee's medical needs and restrictions, or withholding information about worksite hazards, the conduct still falls short of the kind of actual intention to injure that robs the injury of accidental character [@Larson2020, $\S$ 103.03]. 

Plaintiffs may also file wrongful death suits in hopes that courts will disregard exclusivity in a pandemic context on policy grounds or pursue suits where disputes exist as to the identity of an employer. Suits involving fast food restaurants, for example, may name restaurant franchisors as defendants on the theory that franchisees are the actual employers of employees. Franchisors as non-employers may not be subject to exclusivity. But non-employer franchisors may also possess inadequate control of working conditions to support a claim of "intentional" subjection of someone else's employees to workplace hazards.  

## Exclusivity and Public Nuisance Suits

Plaintiffs have also filed public nuisance tort suits as an apparent strategy to compel employers to make workplaces safer from COVID-19. A public nuisance is "an unreasonable interference with a right common to the general public." Restatement (Second) of Torts $\S$ 821B(1) (1979). An interference is unreasonable if it significantly affects the public health, the public safety, the public peace, the public comfort, or the public convenience. Id. $\S$ 821B(2).

Maintaining businesses not in compliance with COVID-19 safety protocols seems to fall within the definition. Tort law has traditionally carefully limited public nuisance liability. Even if the general public suffers harm, individual plaintiffs may bring private actions for public nuisance only if they have suffered a special injury, i.e., a "harm of a kind different from that suffered by other members of the public exercising the right common to the general public that was the subject of interference." Restatement (Second) of Torts $\S$ 821C. Usually, plaintiffs not eligible for tort damages also may not obtain tort injunctions. Id. $\S$ 821C, comment j.

More importantly, worker compensation exclusivity seems likely to bar public nuisance lawsuits if brought by employees to obtain damages from their employers. Although exclusivity issues normally arise in negligence or wrongful death contexts, courts have found exclusivity rule to bar a wide array of civil actions, including claims under the Federal Employer Liability Act, the Jones Act, the Federal Tort Claims Act, admiralty law, and state structural work and defective machinery statutes [@Larson2020, $\S$ 100.03]. One treatise states: "The workers' compensation remedy is exclusive, absent a statutory or judicial exception, for all work-related claims. The theory of recovery is immaterial." [@MWC2020, $\S$ 102:1]. In the few cases involving conflicts between public nuisance and workers' compensation exclusivity, the courts found exclusivity to bar public nuisance claims. See [Acevedo v. Consolidated Edison Co., 189 A.D.2d 497 (N.Y. 1993)](https://casetext.com/case/acevedo-v-con-ed); [Bowden v. Young, 120 So. 3d 971 (Miss. 2013)](https://casetext.com/case/in-re-bowden-6); [Cunningham v. Anchor Hocking Corp., 558 So. 2d 93 (Fla. 1990)](https://casetext.com/case/cunningham-v-anchor-hocking-corp); [Rodgers v. GCA Servs. Group, 2013 Tenn. App. LEXIS 99](https://casetext.com/case/rodgers-v-gca-serv-grp); [Wilburn v. Boeing Airplane Co., 188 Kan. 722, 731 (Kan. 1961)](https://law.justia.com/cases/kansas/supreme-court/1961/42-298-0.html). Thus, if the theory of a suit -- including a public nuisance suit -- involves employee physical harm from COVID-19, workers compensation exclusivity will very likely bar that suit.

The picture is less clear where plaintiffs seek _only_ injunctive relief -- a type of remedy that  the workers' compensation system does not provide. Public nuisance law normally requires that in order to obtain an injunction "one must have the right to recover damages, . . ., or have authority as a public official or public agency to represent the state or a political subdivision in the matter, . . . or have standing to sue as a representative of the general public, as a citizen in a citizen's action or as a member of a class in a class action." Rest. 2d Torts $\S$ 821C(2). If plaintiffs are not public officials, and do not have "representative standing" to bring claims, do they possess the "right to recover damages" in light of exclusivity? No cases addressing the question have been located.

On the one hand, one might argue that, because of exclusivity, employees may not obtain public nuisance "damages" for "special injuries," which would almost certainly involve work-related physical harms. Without the right to obtain damages, the argument would continue, no right to obtain injunctions exists. On the other hand, one might argue that once employees have proven a "special injury" of a type ordinarily recognized in public nuisance claims, they can seek injunctions. On this reading, the "right" to damages assures that plaintiffs have just enough of a real and concrete dispute ("standing") -- necessary for a court to hear a case at all -- and thus protects defendants from multiple lawsuits filed by minimally impacted members of the general public. The ability to actually _receive_ damages is irrelevant; the concrete "right" to damages controls.

But plaintiffs may have a hard time proving that they suffered "special injury" to bring a public nuisance suit, because a special injury has to be different in _kind_ from what the general public suffers, not just "the same kind of harm or interference but to a greater extent or degree." Rest. 2d. Torts, $\S$ 821C, cmt. B. Employees exposed to COVID-19 at work arguably suffer from risks of the same kind of harm as the general public. On the other hand, should employees' risk of exposure become sufficiently elevated over the general public's risk, it may cross a threshold into a different kind of harm. Rest 2d. Torts $\S$ 821C, cmt. C. 

No case guidance exists in this area. The three COVID-19 suits raising public nuisance issues were decided without written analysis of these issues. Two state court decisions issued in favor of employees in cases filed against McDonald's franchisees. [Massey v. McDonald's Corp., No. 2020-CH-04247 (Ill. Cir. Ct. 2020)](https://images.law.com/contrib/content/uploads/documents/292/69750/McDonalds-ruling-6.24.20.pdf) (factual discussion of public nuisance but no legal analysis); [Hernandez v. VES McDonald's, No. RG20064825 (Cal. Super. Ct., June 22, 2020)](https://aboutblaw.com/RBu) (restaurant required to close but no analysis of public nuisance issue). A Federal District Court in Missouri dismissed a case filed against Smithfield Foods on administrative law grounds without reaching a public nuisance claim [@Duff2020a; @Duff2020b]. A public nuisance lawsuit filed in New York against Amazon on June 3 has also been dismissed. [Memorandum Decision and Order, Palmer v. Amazon.com, No. 1:20-CV-02468 (E.D.N.Y., November 1, 2020](https://cases.justia.com/federal/district-courts/new-york/nyedce/1:2020cv02468/448693/73/0.pdf?ts=1604410789). There has been so much talk but so little legal litigation on public nuisance, and that suggests how difficult it is for employees to prevail on such claims.        

