# Lost Wage Assistance

_Sachin S. Pandya_, 2020-09-19

On August 8, 2020, admist stalled negotiations over extending the FPUC, President Trump issued a [memorandum](https://www.whitehouse.gov/presidential-actions/memorandum-authorizing-needs-assistance-program-major-disaster-declarations-related-coronavirus-disease-2019/) authorizing the Federal Emergency Management Agency (FEMA) to provide "lost wages assistance" (LWA) pursuant to section 408(e) of Stafford Act, the main federal law authorizing disaster relief. Under this program, unemployed workers already eligible for at least \$100/week in State unemployment insurance benefits could apply to get an additional \$300/week until LWA funds -- roughly a month or so. On paper, this aid was _not_ disaster assistance for the unemployed under Stafford Act section 410, but so-called "other needs" assistance under section 408(e) of that Act. 

Critics called the LWA a poor substitute for the \$600/week FPUC benefit that had expired in July [e.g., @Stettner2020]. By early September 2020, FEMA had approved forty-eight States and the District of Columbia to receive grants under the LWA program [@FEMA2020].

This Chapter explains the disconnect between the LWA and how Stafford Act other-needs assistance is supposed to work by law.  In short, Stafford Act other-needs assistance is only supposed to cover eligible costs _already incurred_ to obtain items or services essential to one's ability to prevent, mitigate, or overcome a disaster-related hardship, injury or adverse condition on a per-item or per-service basis. The LWA flat amount -- \$300/week -- is not tied to the cost of any such item or service in this way.  Accordingly, the LWA seems like an effort by Trump Administration lawyers to use disaster relief funds for unemployment relief while avoiding the restrictions associated with Stafford Act unemployment disaster assistance for the unemployed under Stafford Act section 410.

## Disaster Relief

The Stafford Act authorizes disaster relief once the President declares an emergency or (more relevant here) a "major disaster", a term that the Act defines to mean 

>any natural catastrophe (including any hurricane, tornado, storm, high water, winddriven water, tidal wave, tsunami, earthquake, volcanic eruption, landslide, mudslide, snowstorm, or drought), or, regardless of cause, any fire, flood, or explosion, in any part of the United States, which in the determination of the President causes damage of sufficient severity and magnitude to warrant major disaster assistance under this chapter to supplement the efforts and available resources of States, local governments, and disaster relief organizations in alleviating the damage, loss, hardship, or suffering caused thereby.

42 U.S.C. § 5122(2). Though it does not expressly refer to a disease outbreak like COVID-19, an influenza epidemic neither clearly falls within or outside of the term "natural catastrophe" in this definition [@Liu2008]. In any case, by late April 2020, the President had approved COVID-19-related "major disaster" declarations for all fifty States, the District of Columbia, Puerto Rico, the Virgin Islands, Guam, American Samoa, and the Northern Mariana Islands [@Webster2020, app. A].

Once a "major disaster" declaration issues, the Stafford Act authorizes the President to provide several types of disaster aid, including unemployment aid (section 410 of the Act) and "other-needs" assistance (section 408(e) of the Act).  

Any type of Stafford Act typically comes a key string attached: Anyone who gets Stafford Act aid "shall be liable to the United States to the extent that such assistance duplicates benefits available to the person for the same purpose from another source." 42 U.S.C. § 5155(c). In other words, if you received or _could have received_ benefits from another source that even partly duplicates your Stafford Act benefits, you are in now in debt to the US government to that extent. See 44 C.F.R. § 206.116(a) (governing "recovery of funds"); 44 C.F.R. § 206.113(b)(7)(applicant must agree to "refund to FEMA or the State any portion of the assistance that the applicant receives or is eligible to receive as assistance from another source"); and State of Hawaii ex rel. Atty. Gen. v. FEMA, 294 F.3d 1152, 1159 (9th Cir. 2002) ("'benefits available' is unambiguous in that it cannot refer only to benefits actually received"). The President, however, can waive this requirement. 42 U.S.C. § 5155(b)(4). The LWA memorandum does not indicate that the President has done so. 

## Unemployment Assistance

Once a "major disaster" declaration issues, the Stafford Act authorizes the President to provide unemployment aid to workers laid off because of the disaster who otherwise wouldn't qualify under State UI law. Section 410 of the Stafford Act authorizes the President to provide "to any individual unemployed as a result of a major disaster such benefit assistance as he deems appropriate" while that individual is unemployed. 

But section 410 restricts such aid in several ways. The unemployed individual _cannot_ be "entitled to any other unemployment compensation." [42 U.S.C. § 5177(a)](https://www.govinfo.gov/content/pkg/USCODE-2018-title42/html/USCODE-2018-title42-chap68-subchapIV-sec5177.htm). Disaster unemployment assistance only lasts "as long as the individual's unemployment caused by the major disaster continues or until the individual is reemployed in a suitable position," but no longer than 26 weeks after the major disaster is declared. The amount can't be more than the maximum under the UI law of the State "in which the disaster occurred." Id. Department of Labor (DOL) regulations set forth eligibility requirements for such relief, including that the "individual is able to work and available for work within the meaning of the applicable State law." 20 C.F.R. § 625.4(g). Notably, eligibility does not depend on "employee" status; it extends to either an unemployed worker or "an unemployed self-employed individual," id. § 625.4(c).

## Other-Needs Assistance and the LWA

Section 408(e) of the Stafford Act -- titled "Financial assistance to address other needs" -- provides that for any individual or household adversely affected by a major disaster, the President can provide not only financial assistance to "meet disaster-related medical, dental, child care, and funeral expenses," but also financial assistance "to address personal property, transportation, and _other necessary expenses or serious needs_ resulting from the major disaster." [42 U.S.C. § 5174(e)](https://uscode.house.gov/view.xhtml?req=granuleid:USC-prelim-title42-section5174&num=0&edition=prelim) (emphasis added).

FEMA regulations, not DOL regulations, govern other-needs assistance, including by specifying the "eligible costs" that other-needs assistance covers for certain items or services, [44 C.F.R. §§ 206.119(c)](https://www.ecfr.gov/cgi-bin/text-idx?SID=dd7329776ce2c3d5c330142b6a548d8a&mc=true&node=se44.1.206_1119&rgn=div8), as well as a catch-all for "[o]ther miscellaneous items or services that FEMA, in consultation with the State, determines are necessary expenses and serious needs". Id. § 206.119(c)(6)(ii). 

In turn, FEMA defines "necessary expense" to mean "the cost associated with acquiring an item or items, obtaining a service, or paying for any other activity that meets a serious need." [44 C.F.R. § 206.111](https://www.ecfr.gov/cgi-bin/text-idx?SID=dd7329776ce2c3d5c330142b6a548d8a&mc=true&node=se44.1.206_1111&rgn=div8). And the term "serious need" means "the requirement for an item, or service, that is essential to an applicant's ability to prevent, mitigate, or overcome a disaster-related hardship, injury or adverse condition." Id.  

Items that might be covered by this "miscellaneous items or services" catch-all provision include a generator, chainsaw, humidifier, and weather radio. Among the eligibility conditions, the "expense must be direct result of the disaster" and applicants must "provide an itemized receipt or equipment rental agreement for eligible expenses." And other-needs assistance for miscellaneous items is subject to the amount limit "established for the item by the state, territorial, or tribal government. [@FEMA2016, 102-103]

The problem: FEMA can provide section 408(e) other-needs assistance to an individual or household _only_ "[w]hen the individual or household has incurred a disaster-related necessary expense or serious need," [44 C.F.R. § 206.113(a)(1)](https://www.ecfr.gov/cgi-bin/text-idx?SID=dd7329776ce2c3d5c330142b6a548d8a&mc=true&node=se44.1.206_1113&rgn=div8), and may not provide other-needs assistance "[f]or any items not otherwise authorized by this section," id. § 206.113(b)(10).  Thus, other-needs assistance is only supposed to cover eligible costs _already incurred_ to obtain items or services essential to one's ability to prevent, mitigate, or overcome a disaster-related hardship, injury or adverse condition on a per-item or per-service basis.  The LWA flat amount, however, is not tied to the cost of any such item or service in this way. 

Thus, the LWA seems like an effort by Trump Administration lawyers to use disaster relief funds for unemployment relief while avoiding the restrictions associated with Stafford Act unemployment disaster assistance for the unemployed under Stafford Act section 410, such as that the unemployed individual receiving such assistance is "not entitled to any other unemployment compensation." [42 U.S.C. § 5177(a)](https://www.govinfo.gov/content/pkg/USCODE-2018-title42/html/USCODE-2018-title42-chap68-subchapIV-sec5177.htm).  To the contrary, someone seeking LWA would not qualify unless they qualified under State unemployment insurance for at least \$100/week.

Thus far, no one has filed a lawsuit challenging the LWA as outside the President's authority under section 408(e) of the Stafford Act.
