# Layoffs and Canadian Employment Law {#lyff_canada}

_David J. Doorey_, 2020-10-09

Canada had its first COVID-19 related death on March 9, 2020. By March 18, most provinces had declared states of emergency. Canada closed its border to all non-essential travel by March 20 and within days all non-essential businesses had been ordered closed. By the end of March, the provinces had introduced social distancing rules, sometimes first as recommendations and later as orders subject to sanctions. On March 26, the federal government invoked the little used [Quarantine Act, SC 2005, c 2](http://canlii.ca/t/54b27), to order people returning to Canada to self-isolate for 14 days. By early October, Canada had over 175,000 confirmed cases and over 9,500 deaths [@GovCanada2020].  Because of high infection rates in the U.S., the Canadian government kept its southern border closed to all non-essential traffic into at least October 2020 [@Simpson2020].

COVID-19 devastated the labor market in Canada. Some 3 million Canadian jobs were lost in March and April and the official unemployment rate reached nearly 14 percent [@StatCanada2020]. Nearly one-third of the Canadian workforce either lost their job or suffered a reduction in hours. The federal government responded primarily with a stimulus package to support employers and workers.

This Chapter discusses how Canada provided the Canadian Emergency Response Benefit (April 2020), and then replaced it with new temporary benefits under the Canada Recovery Benefits Act (Sept. 2020), for workers that, due to COVID-19, were laid off or became underemployed when, for example, their employers closed due a lack of business or government decree; they contracted COVID-19 and were quarantined; they had to care for a family member with COVID-19; or their child's school or day care closed. With these benefits, Canada addressed the fact that many workers in these situations did not qualify for benefits under Canada's normal unemployment insurance legislation.

Moreover, the need for employers to terminate or temporarily lay off workers during the pandemic raised a number of interesting and novel employment law problems. Here, we discuss the statutory and common law obligation on Canadian employers to provide employees with notice of termination and the doctrine of constructive dismissal, which in many cases treats temporary layoffs as a fundamental breach of the employment contract.

## The Canadian Emergency Response Benefit

Although jurisdiction over most Canadian employment relations falls primarily to provincial governments, Canada's federal government -- unlike the U.S. federal government -- has exclusive authority over unemployment insurance benefits. [The Constitution Act, 1867, 30 & 31 Vict, c 3, s. 91(2A)](http://canlii.ca/t/ldsw#sec91). The key statute, the [Employment Insurance Act, SC 1996, c 23](http://canlii.ca/t/54qgm) (EIA), provides "regular" and "special" unemployment benefits, albeit to only about 40 percent of unemployed workers [@Gray2016].

"Regular benefits" pay an amount based on prior employment earnings (around 55 percent) to eligible unemployed workers for a period ranging from 14 to 45 weeks. Eligibility is tied to a complex formula of "insurable employed hours" worked during a "qualifying period" (usually 52 weeks). The number of insurable hours required to qualify for regular benefits depends on the unemployment rate in the region of the country where the applicant lives, but ranges from 420 to 700 hours. [EIA, s. 7(2)]( http://canlii.ca/t/54qgm#sec7subsec2).  Once qualified, recipients receive benefits for a period ranging from 14 to 45 weeks depending on the unemployment rate in the region where the employee lives and the number of their insurable employed hours. [EIA, s. 12(2)](https://www.canlii.org/en/ca/laws/stat/sc-1996-c-23/178239/sc-1996-c-23.html#sec12subsec2).  This model typically disqualifies millions of Canadians whose work differs from the traditional standard form of full-time employment, including part-time, seasonal, temporary, and gig work--forms of work that are dominated by women, new immigrants, and people of colour [@Vosko2011]. 

"Special benefits" include sickness, maternity, parental, and compassionate care benefits. [EIA s. 12(3)](http://canlii.ca/t/54qgm#sec12subsec3). Special benefits align with entitlement to various unpaid leaves of absence protected in provincial labor standards legislation. For example, some provincial governments introduced a right to take unpaid leave for various COVID-19 related reasons, including caring for children whose schools were closed. E.g., [Ontario Bill 186, 2020](https://www.ola.org/en/legislative-business/bills/parliament-42/session-1/bill-186). Workers who took this or other types of statutorily protected leave could qualify for EIA special benefits. Moreover, employees who contracted COVID-19 or who were required to care for a critically ill family member who contracted the disease were eligible to claim EIA sickness or compassionate care benefits.

In response to the pandemic, Canada enacted a massive stimulus package in April 2020 that included CERB, the flagship program to assist workers who lost work due to COVID-19. Until early October 2020, the CERB provided payments of \$500 per week for up to 28 weeks to Canadian workers who: were 15 or older; had not voluntarily quit their job; had earned at least \$5000 from employment, self-employment, or social benefits in the 12 months prior to their CERB application; had earned not more than \$1000 in the 4 week period prior to their application for CERB benefits; and had lost income due to COVID-19 related reasons [@CERBa]. Eligibility for CERB funds was broader than normal unemployment insurance benefits. By eliminating the requirement for previous "employed" hours, the CERB reached more precarious workers than the EIA, including independent contractors, although worker advocates still criticized CERB for not covering more workers [@Langille2020]. Over 8.8 million Canadians applied for CERB benefits and over CDN$80 billion had been paid out by late September [@CERBb].  

## Temporary Reform and the Canada Recovery Benefit Act

By September 27, 2020, Canada had phased out the CERB and replaced with a complex array of alternative funding options with stricter qualifying criteria. Firstly, the federal government revamped the EIA rules effective until September 2021 by, among other changes, substantially reducing the number of required "insurable hours" to qualify for EIA benefits to 120 hours and by introducing a new "floor" of at least $400 per week for eligible recipients. [SOR/2020-187](http://gazette.gc.ca/rp-pr/p2/2020/2020-09-16/html/sor-dors187-eng.html).  Unlike CERB recipients, EIA benefit recipients must file regular reports showing that they are willing and able to work. Also unlike CERB payments, taxes are withheld from EIA payments.

Secondly, for workers who do not qualify for the revised EIA benefits, the federal government introduced three new benefits -- the Canada Recovery Benefit, the Canada Recovery Sickness Benefit, and the Canada Recovery Caregiving Benefit -- for Canadians until September 2021. Canada Recovery Benefits Act, [Bill C-4 2020](https://parl.ca/DocumentViewer/en/43-2/bill/C-4/third-reading), s. 3, 10, 17.

The Canada Recovery Benefit (CRB) is available to Canadians 15 years of age or older who, due to COVID-19, either were not working or had a reduction in their average weekly income of 50% of more compared to last year and who earned at least \$5000 in income in the previous 12 months. The CRB pays out \$900 every two weeks (after withheld tax deductions) for up to 26 weeks. The Canada Recovery Sickness Benefit (CRSB) is for Canadians unable to work because they are sick or quarantined due to COVID-19.  The Canada Recovery Caregiving Benefit (CRCB) is for Canadians unable to work because they must provide care for family members or children under the age of 12 who are home due to closure of schools, daycares, or other care facilities. To qualify for these benefits, one must have also earned at least \$5000 in income in the previous 12 months.  Recipients of both the CRSB and the CRCB receive \$450 per week (after tax withholding) for up to 26 weeks in the case of the CRCB and only two weeks in the case of the CRSB.

According to estimates from the think-tank Canadian Centre for Policy Alternatives (CCPA), approximately 2.1 million of the about 4 million CERB recipients in late September 2020 could transfer from the CERB benefit to the revised EIA benefits [@CCPA2020a].  Approximately 900,000 CERB recipients would be eligible for the new CRB, including many self-employed workers.  Approximately 184,000 would be eligible for the new CRCB initially, and only a small number of people were expected to apply for the CRSB.  Approximately 776,000 Canadians who had been eligible for the CERB would no longer be eligible for any of the new benefit alternatives available as of October 2020 [@CCPA2020b]. The CCPA estimated that 25 percent of CERB recipients will be worse off under the new model, whereas about 336,000 Canadians who did not qualify for CERB would be gain some support under the revised EIA rules.

## Notice of Termination, Temporary Layoffs, and Frustration of Contract

COVID-19's economic impact has prompted questions about whether a temporary or permanent layoff due to a COVID-19 related business downturn would trigger the legal duty on the employer to provide the employee with notice of termination. Since the early 20th century, Canadian common law provides that employment contracts implicitly oblige employers to provide "reasonable notice" of termination of the employment contract, unless the contract expressly indicates otherwise. That notice can take the form of working notice -- the employee works out the notice period -- or pay in lieu of notice. Courts determine the amount of notice by applying well-known criteria explained in a leading 1960 decision called [Bardal v. Globe & Mail Ltd. (1960), 24 D.L.R. (2d) 140 (Ont. H.C.)](https://www.canlii.org/en/on/onsc/doc/1960/1960canlii294/1960canlii294.html), the most important of which has always been length of service [@Doorey2020a]. The longer an employee is employed, the longer the period of notice required. Reasonable notice can range from as little as two weeks to as much as two years or more for very long tenure employees.

Because the implied obligation to provide notice of termination is a default rule,  employers could bypass it by including a clause in employment contracts that expressly defines how much notice is required, or by providing that the contract is "at will". However, beginning in the 1960s, Canadian legislators introduced statutory minimum notice of termination obligations. e.g., [Ontario Employment Standards Act, s. 57](https://www.canlii.org/en/on/laws/stat/so-2000-c-41/latest/so-2000-c-41.html#sec57), which employers cannot avoid by contract. In general,  the required statutory notice ranges from one to eight weeks depending on length of service.

In general, if an employer must provide notice of termination of an employment contract, that obligation applies to terminations due to a permanent closure of a business. However, in practice, employees rarely recover damages when their employer fails to provide notice and becomes insolvent, because those damages are treated as unsecured debts in Canadian bankruptcy and insolvency law.  Therefore, many employees who lose their jobs because their employer closes entirely due to COVID-19 related reasons would likely recover little more than their unpaid wages up to the amount of \$2000, a claim which is treated as secured under the Federal Bankruptcy and Insolvency Act (BIA), [R.S.C. 1985, c B-3, s. 81.3]( https://www.canlii.org/en/ca/laws/stat/rsc-1985-c-b-3/latest/rsc-1985-c-b-3.html?autocompleteStr=bankruptcy%20&autocompletePos=1#sec81.3subsec1).

However, even if a business remains a viable concern, the doctrine of "frustration of contract" might relieve the employer of the usual common law and statutory obligations to provide notice of termination to any employees who are terminated  due a lack of work caused by COVID-19. Frustration of contract occurs when it becomes impossible to perform the contract as initially envisioned due to unforeseen circumstances that are the fault of neither party [@Doorey2020c]. The classic example involves destruction of workplaces by so-called Acts of God, such as tornados, floods, and fires. However, a Canadian court might extend the frustration of contract doctrine to the case of job losses caused by a global pandemic. That would render the contract void and eliminate future obligations, including the requirement to provide common law notice of termination [@Doorey2020b].

Some Canadian labor standards statutes also incorporate the common law doctrine of frustration of contract.  For example, the Ontario Employment Standards Act provides that statutory notice is not required when the employment contract has "become impossible to perform or has been frustrated by a fortuitous or unforeseeable event or circumstance". [Ontario Regulation 288/01, s. 2(1)4](http://canlii.ca/t/5327n#sec2subsec1).  There is a reasonable argument that terminations due to a collapse of a business brought about a global pandemic meet the test for frustration of contract, although that argument has not yet been tested in either the courts or before any of Canada's labor standards tribunals.

COVID-19 also raised the possibility that thousands of Canadian employees would respond to their temporary layoff or reduction in their hours by suing their employers for "constructive dismissal". Canadian common law typically provides that, absent a contract term to the contrary, if an employer temporarily lays off a non-union employee, or cuts that employee's hours and pay by more than a de minimis amount, the employer commits a fundamental breach of contract that the employee can treat as having terminated the contract. This is known as a "constructive dismissal". [Elsegood v. Cambridge Spring Service, 2011 ONCA 831](http://canlii.ca/t/fpgmf). In other words, an employee who is told to go home until business picks up can elect instead to quit and sue the employer in court for failure to provide notice of termination.  As discussed above, it is unclear whether, in response, the employer could prevail on a defense of frustration of contract.

Canada's labor standards statutes treat temporary layoffs differently from the common law.  Those statutes require employers to provide notice of termination whenever an employee's contract is "terminated", but temporary layoffs do not become "terminations" under the statutes until they continue beyond a defined period of time i.e., it exceeds 13 weeks in any 20 week period. [Ontario ESA, s. 56(2)]( https://www.canlii.org/en/on/laws/stat/so-2000-c-41/latest/so-2000-c-41.html#sec56subsec2).  As time passed, many "temporary layoffs" that started in March or early April approached the statutory threshold that would convert the temporary layoff into a "termination" and thereby trigger the employer's statutory obligation to pay out wages based on the length of statutory notice.

To avoid a COVID-19 related temporary layoff automatically being deemed a termination by labor standards legislation, some provincial governments extended the length of time that a layoff can last before it is deemed to be a termination. E.g. [Alberta Bill 32, 2020, s. 17](https://docs.assembly.ab.ca/LADDAR_files/docs/bills/bill/legislature_30/session_2/20200225_bill-032.pdf).  Other provinces achieved the same outcome by deeming employees who experienced temporary layoffs due to COVID-19 related reasons to be on statutorily protected unpaid leaves of absence rather than layoffs. E.g. [Ontario Regulation 228/20, 2020](https://www.ontario.ca/laws/regulation/r20228), s. 4. These moves were a mixed blessing for employees -- their right to statutory notice pay was eliminated or at least delayed, but if they had hopes of returning to their jobs, their contracts remained alive legally speaking.

Canadian governments responded to the effects of COVID-19 on labor markets through a mix of temporary emergency funding measures and piecemeal legislation that altered or temporarily suspended the law that typically applies to the termination of employment contracts.  It will take months if not years before we know how well these measures distributed COVID-19's harm to Canadian workers and businesses.
