# (PART\*) Disability and Disparity {-} 

# COVID-19 Employee Health Checks, Remote Work, and Disability Law {#disability}

_Elizabeth Pendo_, 2021-02-03
 
The Americans with Disabilities Act (ADA) prohibits discrimination against people with disabilities, about 61 million individuals in the U.S. [@Okoro2018].  The law's protections in the workplace are especially important during COVID-19, which has worsened pre-existing disparities experienced by people with disabilities [@BLS2020b; @Brucker2015]. The ADA also applies to new strategies to reduce the risk of COVID-19 infection in the workplace.  This Chapter will focus on two strategies that impact individuals with and without disabilities -- employee health screening, testing and vaccination policies, and new or expanded remote work programs.
 
## The Americans with Disabilities Act

Title I of the ADA bars an employer from discriminating against "a qualified individual on the basis of disability" in regard to job application procedures, hiring, promotion, firing, compensation, job training, and other terms, conditions, and privileges of employment. [42 U.S.C. $\S$ 12112(a)](https://www.govinfo.gov/content/pkg/USCODE-2018-title42/html/USCODE-2018-title42-chap126-subchapI-sec12112.htm). A "qualified individual" is someone "who, with or without reasonable accommodation, can perform the essential functions of the [job]." [42 U.S.C. $\S$ 12111(8)](https://www.govinfo.gov/content/pkg/USCODE-2018-title42/html/USCODE-2018-title42-chap126-subchapI-sec12111.htm).  The ADA requires an employer to make "reasonable accommodations" to the known limitations of a qualified individual, [id. $\S$ 12112](https://www.govinfo.gov/content/pkg/USCODE-2018-title42/html/USCODE-2018-title42-chap126-subchapI-sec12112.htm), within certain limits. The ADA also limits an employer's ability to require medical examinations or ask questions related to disability. [Id. $\S$ 12112(d)](https://www.govinfo.gov/content/pkg/USCODE-2018-title42/html/USCODE-2018-title42-chap126-subchapI-sec12112.htm).

The ADA protects individuals who fall within its definition of disability: 

>The term "disability" means, with respect to an individual--(A) a physical or mental impairment that substantially limits one or more major life activities of such individual; (B) a record of such an impairment; or (C) being regarded as having such an impairment . . . .

[42 U.S.C. $\S$ 12102(1)](https://www.govinfo.gov/content/pkg/USCODE-2018-title42/html/USCODE-2018-title42-chap126-sec12102.htm). The definition of disability is meant to be interpreted broadly. For example, the term "major life activities" includes a long, non-exclusive list of activities and functions, including the operation of bodily systems and organs, such as the immune system, normal cell growth, digestive, bowel, bladder, neurological, brain, respiratory, circulatory, endocrine, and reproductive functions. Id. $\S$ 12102(2)(B). As a result, although disability must be assessed on a case-by-case basis, physical impairments such as cancer, lung disease, serious heart conditions, immune-suppressing conditions, and diabetes are considered ADA disabilities "in virtually all cases."  [29 C.F.R. $\S$ 1630.2(j)(3)(ii)](https://ecfr.federalregister.gov/current/title-29/subtitle-B/chapter-XIV/part-1630/section-1630.2#p-1630.2(j)(3)(ii)). High blood pressure can also be an ADA disability, because it impairs the cardiovascular or circulatory systems, even when "mitigat[ed]" or controlled by medication, id., $\S$ [1630.2(j)(1)(vi)](https://ecfr.federalregister.gov/current/title-29/subtitle-B/chapter-XIV/part-1630/section-1630.2#p-1630.2(j)(1)(vi)). The Centers for Disease Control and Prevention (CDC) recognizes these underlying health conditions as putting individuals at greater risk of severe illness from COVID-19 [@CDC2020b].

The pandemic also has negatively impacted the mental health of the population at large [@Panchal2020]. New and preexisting mental health conditions can be ADA disabilities.

Can COVID-19 infection itself qualify as an ADA disability? It is possible, depending on the individual’s specific circumstances. The Equal Employment Opportunity Commission (EEOC) – the agency charged with enforcing the ADA – said in a March 27, 2020 webinar that "it is unclear at this time whether COVID-19 is or could be a disability under the ADA" noting that the virus is "very new" and "there is still much that is unknown." [@EEOC_webinar] However, it can qualify as an ADA disability under existing law. 

First, COVID-19 infection itself can be a _physical impairment_ because it affects the immune system and normal cell growth even absent clinical symptoms. [29 C.F.R. $\S$ 1630.2(h)(1)](https://www.ecfr.gov/cgi-bin/text-idx?SID=28cadc4b7b37847fd37f41f8574b5921&mc=true&node=pt29.4.1630&rgn=div5#se29.4.1630_12). The Supreme Court has held, for example, that an individual with asymptomatic HIV infection has a physical impairment from the moment of infection. [Bragdon v. Abbott, 524 U.S. 624 (1998)](https://scotuslink.com/524/624).

Second, COVID-19 infection can _substantially limit_ a "major life activity" of the individual because it affects the operation of bodily systems and organs. It affects the immune system and normal cell growth even absent clinical symptoms. It is known to significantly impact the lungs, and emerging evidence suggests that it can impair the function of the heart, kidney, liver, brain, blood and blood-forming organs, eyes and skin, and the gastrointestinal, endocrine, and nervous systems [@Gupta2020].  Some reports indicate that the effects of COVID-19 may persist long after the infection subsides [@Cooney2020; @Mayo2020]. It can also be transmitted to others even absent clinical symptoms, which limits the ability to safely interact with others.

An employee who was fired because of actual or perceived COVID-19 infection also may be protected as an individual "regarded as" having an ADA impairment.  Again, the assessment depends on the specific circumstances. For example, an impairment that is both "transitory" (expected to last 6 months or less) and minor will not meet the "regarded as" standard. [42 U.S.C. $\S$ 12102(3)(B)](https://www.govinfo.gov/content/pkg/USCODE-2018-title42/html/USCODE-2018-title42-chap126-sec12102.htm). Also, although individuals who meet only the “regarded as” standard can be protected against workplace discrimination, they are not entitled to reasonable accommodations.      
	  
Some State and local laws also prohibit employer disability discrimination, but they vary in who they cover, what they protect, and how they can be enforced. E.g., [Mich. Comp. Laws $\S$ 37.1202](https://www.legislature.mi.gov/(S(wt1kirsanjwpaxkjotkfr3ue))/mileg.aspx?page=getObject&objectName=mcl-37-1202);  [Calif. Gov't Code $\S$ 12940(a)](https://leginfo.legislature.ca.gov/faces/codes_displayText.xhtml?lawCode=GOV&division=3.&title=2.&part=2.8.&chapter=6.&article=1). For example, New York City prohibits employers from discriminating against any person because of "actual or perceived . . . disability," [N.Y.C. Admin. Code $\S$ 8-107(1)](https://codelibrary.amlegal.com/codes/newyorkcity/latest/NYCadmin/0-0-0-4705), and the city agency that enforces it "considers actual or perceived infection with COVID-19 to be protected as a disability" under that law [@NYCCHR2020].
      
## Employee Health Checks

In light of the COVID-19 pandemic, many employers are taking employee temperatures and asking questions about COVID-19 symptoms. Some are requiring testing for COVID-19 infection. Employee health checks may reveal disabilities and other health conditions that may or may not be tied to COVID-19.  An elevated temperature, for example, could signal a COVID-19 infection, or it could signal stress, pregnancy, or a heart condition.  Many people with disabilities that are hidden or non-obvious choose not to disclose those disabilities to avoid stereotyping, stigma, and discrimination.

The ADA limits the ability of an employer to require medical examinations or ask questions that are likely to reveal information about a disability in order to limit disclosure of disability-related information that workers would otherwise keep to themselves. The ADA regulates medical examinations and disability-related questions for all applicants or employees at three points in time.  First, before an offer is made, the ADA generally bars an employer from requiring medical examinations or asking job applicants disability-related questions. Second, after an offer is made, the employer can require medical examinations and ask disability-related questions as long as it does so for all entering employees in the same job category.

Finally, during employment, an employer can require medical examinations and ask disability-related questions only if they are "job-related and consistent with business necessity." [42 U.S.C. $\S$ 12112(d)(4)(A)]( https://www.govinfo.gov/content/pkg/USCODE-2018-title42/html/USCODE-2018-title42-chap126-subchapI-sec12112.htm). For example, the ADA allows employers to ask about an employee's disability if that employee poses a "direct threat" to workplace health and safety, [42 U.S.C. $\S$ 12113(a)-(b)]( https://www.govinfo.gov/content/pkg/USCODE-2018-title42/html/USCODE-2018-title42-chap126-subchapI-sec12113.htm), i.e., a "significant risk of substantial harm to the health or safety of others" that cannot be eliminated or reduced by a reasonable accommodation. [42 U.S.C. $\S$ 12111(3)](https://www.govinfo.gov/content/pkg/USCODE-2018-title42/html/USCODE-2018-title42-chap126-subchapI-sec12111.htm); [29 C.F.R. $\S$ 1630.2(r)]( https://www.ecfr.gov/cgi-bin/text-idx?SID=956844e465fc90576460a741754fac07&mc=true&node=se29.4.1630_12&rgn=div8).
      
According to the EEOC, employers may screen and test employees for COVID-19 because an employee infected with the virus poses a "direct threat" to health and safety [@EEOC2020c]. Consistent with guidance from the CDC [-@CDC2020a2], the ADA permits reliable and accurate measures such as taking temperatures, asking about symptoms, or testing for present COVID-19 infection.  However, employers may not require or rely on tests for COVID-19 antibodies (evidence of past infection with the virus that causes COVID-19).  The CDC currently advises that antibody tests "should not be used to make decisions about returning persons to the workplace" and that "serologic testing should not be used to determine immune status in individuals until the presence, durability, and duration of immunity are established" [@CDC2020a2]. Accordingly, an antibody test does not meet the ADA's "job related and consistent with business necessity" standard [@EEOC2020c].
      
What if an employee has COVID-19 symptoms or tests positive for COVID-19 infection? An employer can require an employee who has tested positive or who has symptoms to stay home.  However, if the employee is still well enough to perform the job, the employer must  consider whether the threat can be eliminated or reduced through a reasonable accommodation, as described below.  If an employee is at increased risk of COVID-19 due to an underlying health condition that meets the ADA definition of disability, an employer cannot fire or exclude the employee from the workplace without first considering reasonable accommodations.

Can an employer require employees to receive the COVID-19 vaccine when available?  Employers generally have the authority to impose vaccination requirements [YangPendo2020].  The EEOC has said that ADA permits employers to encourage COVID-19 vaccination through voluntary programs [@EEOC2020c], although it is unclear what incentives employers may offer [@PendoHall2019]. The ADA also permits employers to require COVID-19 vaccinations so long as they consider reasonable accommodations for disability and religious reasons under the ADA and related laws [@EEOC2020c].  But there are unresolved legal questions about COVID-19 vaccine mandates under the ADA and other laws because the vaccine was granted Emergency Use Authorization (EUA), which requires recipients receive information about the option to accept or refuse the vaccine. _Id._
   
Employers must keep medical information confidential. The ADA's confidentiality requirements, [42 U.S.C. $\S$ 12112(d)(3)(B),(4)(c)](https://www.govinfo.gov/content/pkg/USCODE-2018-title42/html/USCODE-2018-title42-chap126-subchapI-sec12112.htm), do permit employers to follow directions from the CDC or other public health authorities. For example, the EEOC has advised that an employer may disclose the name of an employee who has COVID-19 to a public health agency, but not to the workplace generally, or to the public absent that employee's consent [@EEOC2020c].  Similarly, the CDC advises that if an employee is confirmed to have COVID-19, employers should notify other employees of possible exposure but maintain confidentiality as required by the ADA [@CDC2020b].

## Remote Work as Disability Accommodation

Remote work has become a much more common practice due to COVID-19.  One-third to one-half of U.S. workers report working from home during the pandemic [@Dingel2020]. While some employers report that they will continue to let employees work remotely in the future [e.g., Copeland2020], others have brought employees back to the workplace.  For employees who have COVID-19 symptoms or infection, or who are at increased risk for serious COVID-19 disease, when does the ADA require employers to provide remote work as reasonable accommodation?

A few lawsuits have been filed based on an employer’s alleged failure to allow remote work as an ADA accommodation in light of COVID-19. E.g., [Complaint, Ferro v. Doctors Healthcare Plans, No. 1:20-cv-23449-BB, 2020 WL 4873160 (S.D. Fla, Aug. 19, 2020)](https://www.courtlistener.com/recap/gov.uscourts.flsd.576237/gov.uscourts.flsd.576237.1.0.pdf). These lawsuits are in early stages, and there are no court decisions to date.  But answers can be found in existing law.
      
The ADA requires that employers provide reasonable accommodations for employees with disabilities, which are affirmative steps that enable employees with disabilities to do their jobs safely and efficiently.  Remote work can be a reasonable accommodation [@EEOC2020c].  Other examples include making workplaces physically accessible, job restructuring, part-time or modified work schedules, reassignment to a vacant position, purchasing accessible equipment or devices, providing readers or interpreters, and modifications to workplace policies, practices, and procedures. [42 U.S.C. $\S$ 12111(9)](https://www.govinfo.gov/content/pkg/USCODE-2018-title42/html/USCODE-2018-title42-chap126-subchapI-sec12111.htm).

Employers, however, do not have to provide accommodations that pose an "undue hardship" (involving significant difficulty or expense) or a "direct threat" (a significant risk of substantial harm to the health or safety of the employee or others, which cannot be eliminated or reduced by a reasonable accommodation). [42 U.S.C. $\S$ 12111(10),(3)](https://www.govinfo.gov/content/pkg/USCODE-2018-title42/html/USCODE-2018-title42-chap126-subchapI-sec12111.htm). For example, an employer can require an employee who has tested positive for present COVID-19 infection or who has COVID-19 symptoms to stay home. However, if the employee is still well enough to perform the job, the employer must consider whether the threat can be eliminated or reduced through a reasonable accommodation, such as working remotely.  Employers must also consider reasonable accommodations for individuals who are at increased risk of COVID-19 due to underlying health conditions that meet the ADA definition of disability.
 
Reasonable accommodation is determined on an individualized basis through a flexible, interactive process between the employer and employee [@EEOC2020c]. Although the ADA does not require that an individual disclose a disability, some disability-related information may be necessary to support a request for reasonable accommodation.  The ADA does not require an employer to provide the specific accommodation that an employee requests, so long as any alternative accommodation it offers adequately address the employee's unique needs and reasonably accommodates the disability. COVID-related health and safety concerns can be addressed through the ADA’s "direct threat" defense [@EEOC2020c].   

To illustrate, suppose an employee asks for remote work as a reasonable accommodation for a disability that puts them at greater risk of serious COVID-19 disease. The employer might refuse that request on the grounds that it has instituted protective measures for on-site workers such as making people wear masks, enhanced cleaning, one-way aisles, or using plexiglass, tables, or other barriers to ensure minimum distances between customers and coworkers. If so, the employer must show that those measures adequately address the "direct threat" to the employee and others in the workplace. Its assessment must be based on an individualized assessment of the risk using the best available objective medical evidence [@EEOC2020c]. The employer would also need to address arguments by the worker that the measures are inadequate. For example, in a classroom, it may be impractical to keep everyone six feet apart at all times, or make sure students consistently wear masks.

Expanded remote work policies may greatly benefit workers with disabilities, among others [@Stengel2020].  But many jobs cannot be done remotely. An estimated 26% of workers continue to work on premises [@Bloom2020, 2]. According to a recent study, educators, managers, and professionals in computer work, business, and law are most likely to be able to work remotely, while many employees in food service, construction, maintenance and repair, and production are unable to perform their jobs remotely [@Dingel2020].
      
In addition, the ADA does not require employers to provide accommodations to employees who are at increased risk of COVID-19 due to a reason other than disability (such as age or ordinary pregnancy) or to non-disabled employees who are in close contact with someone at increased risk due to disability (such as a child with an underlying medical condition) [@EEOC2020c]. Other federal laws prohibit workplace discrimination based on other characteristics, such as age, [29 U.S.C. $\S$ 623](https://www.govinfo.gov/content/pkg/USCODE-2018-title29/html/USCODE-2018-title29-chap14-sec623.htm), or pregnancy, [42 U.S.C. $\S$ 2000e(k)](https://www.govinfo.gov/content/pkg/USCODE-2018-title42/html/USCODE-2018-title42-chap21-subchapVI-sec2000e.htm).
