# (PART\*) Unions {-} 

# Cooperation or Conflict? Australian Union Responses to COVID-19 {#union_aus}

_Anthony Forsyth_, 2020-09-30

Despite a long-term decline in union membership, unions in Australia retain significant political influence through their close relationship with the Australian Labor Party and a labour regulation system under which separate legal instruments set minimum wages and working conditions for 122 different industries or occupations. Australian unions have faced hostility from the regulatory state since 2013 and that continued when the conservative Coalition government was re-elected in May 2019 [@Macneil2020].

Then, in March 2020, along came the COVID-19 pandemic. 

Very quickly, the federal government moved from combating to cooperating with trade union leaders to shut down large parts of industry, transition millions of workers to working from home, and keep essential sectors operating safely. The Australian Council of Trade Unions and the federal Industrial Relations Minister, Christian Porter, established a regular dialogue [@Grattan2020]. Former union leaders were among those appointed to the national body established to tackle the crisis [@NCC2020]. Current union leaders have mostly reciprocated, even though the air of consensus has been tested by business and Coalition government calls for weakening employment protections [@Forsyth2020]. At the same time, some unions engaged in traditional class conflict to protect workers' interests [@Moase2020].

This Chapter shows how two unions in Australia -- the United Workers Union (UWU) and the National Tertiary Education Union (NTEU) -- responded to the COVID-19 pandemic. (The author is a NTEU member and a UWU community member.) Faced with COVID-related recession and unemployment, Australian unions have partly cooperated with business and government to meet these challenges, while also pursuing collective action to counter arbitrary and unfair employer decisions. Six months into this crisis, the UWU has been better able than the NTEU to balance cooperation and conflict in this way.

## Australian Labour Regulation

Unlike American labour law, Australian labour law tends to support trade unions and collective bargaining, though employers have exploited certain limitations in the Fair Work Act 2009 -- the principal federal labour law in Australia [@AJLL2020]. Federal law mostly regulates employment rights and obligations, with state laws generally left to regulate public sector employment. 

The [Fair Work Act 2009, Part 2-4](https://www.legislation.gov.au/Details/C2020C00269), provides several measures to foster  union-based collective bargaining, including an equivalent to the U.S. union-election recognition process; good faith bargaining obligations; assistance in negotiating collective agreements from a specialist tribunal; and union rights to enter business premises for organising activity. Employers, however, can bypass collective bargaining with unions through technical compliance with mechanical agreement-making requirements and by restricting voting on proposed agreements to small cohorts of carefully chosen workers [@Chaudhuri2018, 138]. The Fair Work Act also protects individual employment rights, including prohibitions against unfair dismissal, discrimination, and workplace bullying. [Fair Work Act 2009, Parts 3-1, 3-2, 6-4B](https://www.legislation.gov.au/Details/C2020C00269).

The Australian system also stands out because of the "modern awards": legal documents that set minimum wages and conditions, including leave entitlements, overtime and weekend pay rates, and regulation of working hours, for 122 different industries or occupations [@FWC2020].

## United Workers Union

In late 2019, the United Workers Union (UWU) formed when two unions -- the National Union of Workers and United Voice -- merged.  The UWU has over 150,000 members in more than 45 industries, including warehousing, logistics and the food supply chain; manufacturing; cleaning; security; aged care and disability care; early childhood education; and hospitality [@UWU_web]. Before the merger, the two unions that formed the UWU had adopted several innovations to address falling union membership. These include a whole-of-supply-chain approach to organising workers through the "Fair Food Campaign" [@Underhill2020] and a completely digital union to engage with the young, casualised workforce in cafes, bars and restaurants [@Hospo].

In the early stages of the pandemic, the UWU cooperated with businesses. It jointly applied with employer associations to vary the hospitality and restaurant awards in order to provide businesses with flexibility  to respond to government lockdown measures (for example, to more easily direct employees to change duties or reduce working hours). [Australian Hotels Association and United Workers' Union, [2020] FWCFB 1574](https://www.fwc.gov.au/documents/decisionssigned/html/2020fwcfb1574.htm); [Application to vary the Restaurant Industry Award 2010, [2020] FWCFB 1741](https://www.fwc.gov.au/documents/decisionssigned/html/2020fwcfb1741.htm). The UWU also agreed to work with logistics firm DHL to redeploy workers in areas of the supply chain impacted by closures, such as aviation, to other sites. [DHL Supply Chain (Australia) Pty Limited v. United Workers' Union, [2020] FWC 1581](https://www.fwc.gov.au/documents/decisionssigned/html/2020fwc1581.htm).

At the same time, the UWU led union movement pressure for two key measures to assist workers. First, pandemic leave: the UWU obtained two weeks' paid leave for employees stood-down from their jobs by Star and Crown Casinos in late March [@Hatch2020]. The UWU also sought paid pandemic leave for workers who are required to self-isolate across many other areas of its membership [@UWU2020_3]. 

Secondly, income support: the UWU pushed hard for the (reluctant) Coalition government to introduce the JobKeeper wage subsidy scheme [@jobkeeper]. Under that scheme, the government subsidises businesses that have lost turnover due to the pandemic through payments of A\$1500 per fortnight to eligible employees. The union has continued to highlight JobKeeper's inadequacies (including the lack of support for thousands of casual workers in hospitality and around one million migrant workers), and put forward proposals for a more comprehensive jobs and income guarantee [@Bolton2020].

The UWU also took action, early on, to defend the rights of warehouse workers facing exposure to the virus and greatly increased working hours. In March, the union led a 6-hour strike by members at a cold storage facility run by Coles Supermarkets. The workers were concerned about inadequate safety measures and 10-14 hour working days [@Lopez2020]. 

Increasingly, the UWU has adopted a more confrontational approach, particularly in the state of Victoria. After the initial national success in 'flattening the curve' by May, a resurgence of COVID-19 cases in Melbourne has seen the reinstatement of strict lockdown measures since late June [@Handley2020].   

The rising case numbers in Melbourne have been linked to transmission in many workplaces covered by the UWU, including aged care homes, distribution centres and commercial laundries. Victorian Premier Daniel Andrews pointed to insecure work as a large cause of the outbreak as well as the problem that some low-paid workers continue working while awaiting test results or even having tested positive for coronavirus [@Butler2020; @Schneiders2020].

In this environment, flare-ups over safety issues have become much more common. The UWU has supported workers to resist management directives to continue working, despite heightened COVID-19 risks, in several cases. 

At a Spotless industrial laundry facility on the outskirts of Melbourne, management sought orders from the Fair Work Commission requiring a return to work after workers walked off due to positive tests among the workforce. The dispute centred on the company's decision to shut down and clean only part of the facility, whereas the union argued the whole workplace should be closed and workers stood down with full pay to obtain COVID-19 tests. Because the UWU intervened, the site was temporarily closed following a Victorian health department inspection, and workers received paid leave during this period [@UWU2020_8; @Ananth2020a].

Outbreaks of infection have also occurred at the same Coles cold storage warehouse mentioned earlier; at a Woolworths warehouse supplying alcohol to major retailers; and at a Kmart distribution centre operated by Toll logistics [@Ananth2020b; @Schneiders2020; @Bonyhady2020]. In each instance, UWU members stopped work to demand closure of the site and comprehensive testing of all workers, a "collective stand" to ensure that they were not treated as mere "vectors of transmission" [@Moase2020].

The union held steadfast in that approach as the more serious escalation of COVID-19 cases in Victoria inevitably impacted aged care workers [@Priess2020]. Among other efforts to represent aged care staff, the UWU used the results of a national survey to demand increased training, protective equipment and resources to alleviate the crushing work pressures facing these essential workers [@UWU2020_7].

## National Tertiary Education Union

The NTEU represents academic and general/professional staff employed in universities and technical and further education institutions, with around 30,000 members across Australia [@NTEU_web]  

Over the last 20 years, Australian universities have relied more on revenue from international students, with income from them making up 30-40% of the total revenue of some institutions [@Horne2020]. But when Australia closed its borders to overseas travelers in February-March 2020 -- right at the start of the new academic year -- it massively reduced the numbers of international students commencing their courses. The estimated loss of revenue to the higher education sector for the period 2020-2023, arising from the pandemic, is A\$16 billion [@Ferguson2020].

Initially, universities responded by dismissing large numbers of casual (i.e. temporary) staff and not renewing fixed-term contracts. As the extent of the impact on their revenue base from the loss of future overseas student enrolments became clearer, university leaders began to raise the prospect of deeper staff cuts and the need to reduce pay and conditions if their institutions were to survive the crisis [@Vassiley2020].

The NTEU opposed the early layoffs of casual and fixed-term university staff. Instead, it advocated for more support to teaching staff required to transition to online delivery once campuses closed [e.g. @Convery2020]. The NTEU also campaigned against the federal government's structuring of the JobKeeper wage subsidy scheme to exclude public universities [@Zhou2020].

In mid-May, the NTEU announced that it had negotiated a "National Jobs Protection Framework" (NJPF) with universities that would save up to 12,000 jobs under threat across the sector. This would be achieved through "a time-limited variation to working conditions" which may include university employees being "asked to accept a strictly limited temporary pay freeze or salary reduction" [@NTEU_moa_2020, 3].

The NJPF proposed that temporary pay cuts of up to 15% could be put in place, if approved by a majority vote of staff at any given higher education institution, subject to universities meeting several conditions. These included the prior implementation of management salary reductions, as well as a commitment that no staff would be involuntarily stood down and none would be made redundant unless their work had definitely ceased [@NTEU_moa_2020, 3,5,7,12,15].

However, the NJPF quickly unraveled. Many NTEU members reacted angrily to the proposal. A splinter group called "NTEU Fightback" was swiftly formed to counter the union leadership's position. The Community and Public Sector Union, which covers some non-teaching staff in universities, also opposed the NJPF. Members at some of the NTEU's largest branches, including at Sydney, Melbourne and RMIT universities, passed resolutions condemning the plan [@Mizen2020]. These critics were concerned that the NTEU had too easily given up hard-won conditions, that the job protections in the NJPF were weak, and that the union needed to put more pressure on universities and the federal government to properly fund higher education [@Vassiley2020].

Simultaneously, most university vice-chancellors walked away from the NJPF, no doubt concerned about the membership backlash and  prospect that staff would vote against pay reductions. Under the Fair Work Act, variations to enterprise agreements (which set the pay and conditions for staff at most universities) must be approved by a majority of those voting when the proposed changes are submitted to a ballot of all employees.

In the end, only four of Australia's 39 universities stuck with the NJPF, and by late May the NTEU had withdrawn the proposal altogether [@Vassiley2020]. The union's General Secretary, Matthew McGowan, has since stated that this occurred (in part) because universities were engaged in competitive behaviour and abandoned their own negotiating body, the Australian Higher Education Industrial Association [@McGowan2020]. 

The NTEU then shifted its focus to fighting job losses and protecting members' pay and conditions, although from a weakened position as a result of the NJPF episode. In the months since, many universities have proceeded with large-scale layoffs (both voluntary and targeted redundancies) - for example, 450 jobs were cut at University of Melbourne, 473 at University of New South Wales and 277 at Monash University [@Duffy2020; @Karp2020]. Monash was one of the few remaining adherents to the NJPF, and the university stated that this agreement with the NTEU had prevented a further 190 job losses [@Karp2020]. At Deakin University, the NTEU's intervention slowed down implementation of 400 redundancies. [National Tertiary Education Industry Union v. Deakin University, [2020] FWC 4013](https://www.fwc.gov.au/documents/decisionssigned/html/2020fwc4013.htm).

Management proposals to reduce wages have been approved by staff at some institutions, such as University of Tasmania, and rejected at others including Melbourne University and University of Wollongong [@Ross2020; @Bolton2020]. Other universities have sought to lower costs through measures short of pay cuts, such as arrangements for staff to purchase and take additional annual leave days at Western Sydney University [@WSWS2020]. Universities have generally argued that if staff do not agree to wage reductions or other cost-saving measures, redundancies will follow. However, in some cases, such as at La Trobe University, layoffs have been implemented despite staff acceptance of salary reductions [@Carey2020; @DCruz2020]. 

