# (PART\*) Immigrants {-} 

# Undocumented Worker Relief {#undocumented}

_Sachin S. Pandya_, 2020-09-17

In the U.S., undocumented workers face special challenges under the law because of their immigration status. How did undocumented workers fare differently because of COVID-19? And how did governments and employers respond (or not) to address the distinctive issues faced by those undocumented workers? This Chapter addresses these questions.

## Federal Law Barring State or Local Benefits for Undocumented Workers

Some worker protections and social insurance mechanisms disadvantage workers because they are undocumented. For example, to be federally-certified, a State's unemployment insurance law must provide that to be "available to work" (a showing necessary for benefit eligibility), a UI claimant must, if a non-citizen, be legally authorized to work in the United States. See [20 CFR § 604.5(f)](https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=f6d24b9ec09459c3e1487411a97e871f&mc=true&r=PART&n=pt20.3.604#se20.3.604_15).

More important is a 1996 federal statute, the Personal Responsibility and Work Opportunity Reconciliation Act, Pub. L. No. 104-193, tit. VI, [110 Stat. 2105](https://www.govinfo.gov/content/pkg/STATUTE-110/pdf/STATUTE-110-Pg2105.pdf) (1996) (PRWORA).  Although PRWORA mostly focused on welfare benefits, Title VI of that Act included restrictions on non-citizen access to such benefits, nominally to discourage "illegal immigration" and encourage non-citizens to be "self-reliant". [8 U.S.C. § 1601(5),(6)](https://www.govinfo.gov/content/pkg/USCODE-2018-title8/html/USCODE-2018-title8-chap14-sec1601.htm).

One such PRWORA restriction declared that most kinds of non-citizens (including the undocumented) are "not eligible" for "any State or local public benefit," [8 U.S.C. § 1621(a)](https://www.govinfo.gov/content/pkg/USCODE-2018-title8/html/USCODE-2018-title8-chap14-subchapII-sec1621.htm), defined to include, among other things, any "professional license, or commercial license provided by an agency of a State or local government," _id._ § 1621(c)(1)(A), any "unemployment benefit," id. § 1621(c)(1)(B), as well as a catch-all provision: "any other similar benefit for which payments or assistance are provided to an individual, household, or family eligibility unit by an agency of a State or local government or by appropriated funds of a State or local government," id. Exceptions include "[s]hort-term, non-cash, in-kind emergency disaster relief," id. § 1621(b)(2), and an exception that would cover public health assistance for testing and treatment for COVID-19, see id. § 1621(b)(3).

At the same time, if you apply for a "State or local public benefit", section 1621 doesn't itself require that you must prove that section 1621(a) doesn't apply to you. States and local governments may themselves require such proof, if they choose. [8 U.S.C. § 1625](https://www.govinfo.gov/content/pkg/USCODE-2018-title8/html/USCODE-2018-title8-chap14-subchapII-sec1625.htm).) 

Moreover, Congress left States a way to opt-out:

>A State may provide that an alien who is not lawfully present in the United States is eligible for any State or local public benefit for which such alien would otherwise be ineligible under subsection (a) only through the enactment of a State law after August 22, 1996, which affirmatively provides for such eligibility.

8 U.S.C. § 1621(d). On what counts as an "enactment" and who gets to decide how a State opts out, see @Ayers2018.

Since 1996, some State legislatures have passed laws to trigger the section 1621(d) opt-out for work licenses. E.g., Cal. Bus. & Prof. Code § 135.5; 20 Ill. Comp. Stat. 2105/2105-140. Some of those laws, however, cover only particular occupations or subsets of undocumented workers, such as DACA recipients [@Olivas2017, compiling statutes].

All this meant that, when COVID-19 hit, federal law already made otherwise eligible undocumented workers in most States ineligible for State unemployment insurance and some other State and local public benefits [@Kolker2020].

## The CARES Act and Social Security numbers

Although Congress provided in the CARES Act for pandemic unemployment assistance compensation (PFUC), it required that anyone applying for such aid to use that individual's Social Security number (SSN), not an Individual Taxpayer Identification Number (ITIN), which the IRS issues to those who aren't eligible for an SSN, [26 C.F.R. § 301.6109-1(a)(1)(ii)(B)](https://www.ecfr.gov/cgi-bin/text-idx?node=pt26.20.301&rgn=div5#se26.20.301_16109_61). This requirement effectively excluded undocumented workers, because they are ineligible for an SSN.

The CARES Act similarly required an SSN to be eligible for a refundable tax credit it provided for the 2020 tax year ($1,200, or $2,400 joint filers, plus a $500 credit for each qualifying child under the age of seventeen). [26 U.S.C. § 6428(a)](https://uscode.house.gov/view.xhtml?req=granuleid:USC-prelim-title26-section6428&num=0&edition=prelim). However, this SSN requirement rendered ineligible not only the person without an SSN, but also, in the case of joint filers, that person's spouse, even if the spouse is a U.S. citizen or green-card holder with an SSN. [26 U.S.C. § 6428(g)(1)(B)](https://uscode.house.gov/view.xhtml?req=granuleid:USC-prelim-title26-section6428&num=0&edition=prelim). This restriction did not apply, however, if the spouse was a member of the U.S. Armed Forces at any time during the 2020 tax year, 26 U.S.C. § 6428(g)(3).   

Two lawsuits followed, both filed in Maryland federal district court.  The first challenged this restriction on behalf of the children of parents affected by it. R.V. v. Munuchin, No. 8:20-cv-01148 (D. Maryland, filed May 5, 2020). The argument: it illegally discriminated against the US citizen children of undocumented parents. On June 19, 2020, the district court denied the Government's motion to dismiss. That lawsuit is still pending.

The second lawsuit, filed by sixteen U.S. citizens whose spouses lack legal status, alleged that this restriction violated the U.S. Constitution's Fifth Amendment Due Process Clause by infringing on their fundamental right to choose who to marry; speech and association rights under its First Amendment, by their expression and association with their spouses when they file joint tax returns; and the (implied) equal-protection component of the Fifth Amendment by treating them differently than other married couples. In August 2020, a federal district court judge ruled on the Government's motion to dismiss. Though rejecting the First Amendment speech claim, that judge otherwise denied the motion as to the all the other legal claims. Among other things, the judge rejected the government's argument that § 6428(g)(1)(B) had a rational basis of providing the tax credit only to individuals authorized to work in the U.S. The problem: It applied to eligible individuals with a SSN (the spouse of the couple filing jointly). And that rationale did not square with the exception for SSN holders in the U.S. Armed Forces. [Amador v. Mnuchin, No. ELH-20-1102 (D. Md., Aug. 5, 2020)](https://www2.mdd.uscourts.gov/Opinions/Opinions/20-cv-1102%20Amador.MemorandumOpinion.pdf). That lawsuit is still pending. 

## Disaster relief funds

In response to the exclusions for undocumented workers, some NGOs worked with private philanthropy to create COVID-19 relief funds for anyone not eligible for another type of federal or State aid -- including, but limited to, undocumented, workers [@GCIR2020]. So long as those NGO funds didn't contain "appropriated funds of a State or local government," [8 U.S.C. § 1621(c)(1)(B)](https://www.govinfo.gov/content/pkg/USCODE-2018-title8/html/USCODE-2018-title8-chap14-subchapII-sec1621.htm), the PRWORA restriction didn't apply. To be sure, where the NGO funds didn't ask claimants about their immigration status, there would no proof that the State or local appropriated funds had gone to undocumented workers in any case.

In few places, however, a State or local government committed itself to funding cash payments to undocumented worker suffering because of COVID-19.

### California

On April 15, 2020, California Governor Newsom announced the Disaster Relief Assistance for Immigrants project. California would provide up to \$75 million in one-time cash disaster relief benefits ($500 for an undocumented adult, \$1000 maximum in aid per household) to undocumented Californians, if they showed that had suffered hardship because of COVID-19 and didn't qualify for federal COVID-19 aid. The funds consisted of two parts: \$16.5 million from the State's Rapid Response Program to fund entities to provide "critical assistance to immigrants during times of need," [Cal. Welfare & Inst. Code 13400](https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?sectionNum=13400&lawCode=WIC), and \$63.3 million from a separate appropriation made in March 2020.

Did this relief fund violate the federal statute in 8 U.S.C. § 1621 that bars "State and local public benefits" to undocumented people?  In two lawsuits (filed on behalf of taxpayer plaintiffs by politically conservative NGOs: the Center for American Liberty and Judicial Watch), the plaintiffs argued that it did. Crest v. Newsom, No. 20STCV16321 (Cal. Superior Court, L.A. County, filed April 29, 2019); Benitez v. Newsom, No. S261804 (Calif. Sup. Ct., emergency petition filed April 22, 2020).

In response to the *Benitez* petition, California's Attorney General argued that California had already done enough to have opted out under 8 U.S.C. § 1621(d). Although California law already made undocumented persons ineligible for UI benefits, see [Cal. Unemp. Ins. Code 1264(a)(1)](https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?sectionNum=1264&lawCode=UIC), this was disaster relief, not UI, and the Legislature had already declared that its Rapid Response Program was "a state law that provides assistance and services for undocumented persons within the meaning of [8 U.S.C. § 1621(d)]," [Cal. Welfare & Inst. Code 13403](https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?sectionNum=13403&lawCode=WIC).

What about the other \$63.3 million, which came from a seperate legislative appropriation enacted on March 17, 2020, _not_ directly from the Rapid Response Program?  There, the Caliornia Attorney General's office argued that, in that March 2020 legislation, the Legislature had authorized the Director of California's Department of Finance to allocate those funds to any item for any purpose related to Governor Newsom’s emergency proclamation. [Stats. 2019, ch. 27, § 2](http://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=201920200SB89). About a month later, that Director allocated an additional $63.3 million to the Department of Social Services to fund the emergency relief fund for undocumented persons. Accordingly, the AG concluded, that was enough to satisfy 8 U.S.C. § 1621(d)'s opt-out provision, which after all did not require a state law to expressly refer to section 1621(d) itself. Besides, when it enacted 8 U.S.C. § 1621(d), Congress didn't intend that a State, once it opted out with respect to a State or local benefit, had to do it again every time it appropriated funding for that benefit [@Ferrari2020].

In early May 2020, the California Supreme Court denied the petition in _Benitez_. [Order, Benitez v. Newsom (Cal., May 6, 2020)](https://appellatecases.courtinfo.ca.gov/documents/s261804-order-050620.pdf). The lawsuit in *Crest* is still pending.

The Fund's application window opened on May 18, 2020 and closed on June 30, 2020. By July 1, the Fund had received 150,000 applications for benefits; approved 104,830 of them (about 70%); and disbursed about \$43 million Statewide [@CADSS2020].  By August 27, the Fund had disbursed 150,000 prepaid cards in amounts totaling \$75 million [@CADSS2020a].

### Oregon

In early April 2020, several NGOs created the Oregon Worker Relief Fund to help immigrant workers laid off because of COVID-19. Those NGOs initially raised nearly \$1.5 million in donations for the Fund, including a \$250,000 donation from the city of Portland [@Camhi2020].  By memo dated April 20, 2020, the Director of Portland's Office of Community & Civic Life had recommended the \$250,000 donation to the Fund on the ground that the Fund was led by a coalition of NGOs "to get dollars in the hands of Oregon workers who are being left out of the Federal Stimulus package due to their immigration status. . . . The City’s early commitment to the fund would help generate momentum for additional public sector contributions." [Memo, p. 10](https://www.portlandoregon.gov/cbo/article/759912).

On April 23, 2020, the Oregon Legislature's Joint Emergency Board -- a legislative committee that can allocate state funds from a special Emergency Fund when the Legislature is not in session -- voted to allocate $10 million to the Fund by authorizing a grant to the Oregon Community Foundation to "oversee a culturally-specific community based grant program to make payments to workers who are ineligible for wage replacement payments from traditional unemployment insurance programs." [Oregon Legislative Fiscal Office Certficate para. 4 (April 23, 2020)](https://www.oregonlegislature.gov/lfo/eboard/EB%20Certificate%2004-23-2020.pdf).

By late July 2020, the Oregon Worker Relief Fund had disbursed more than \$10 million in aid [@Goldberg2020].
