# Don't Take the Bus - Private Employer Regulation of Off-Duty, Private Conduct {#privacyoffwork}

_Ann C. Juliano_, 2020-11-29

As COVID-19 began to cross the country, employers started to cancel business travel and prohibit their employees from taking personal vacations. Outraged employees asked "can they do that?" [@Feintzeig2020]. When the New York Stock Exchange reopened the floor on May 25, the Exchange prohibited brokers and employees from taking public transportation [@Pisani2020], although it changed the policy a month later [@Guse2020]. People asked "can they do that?" [@KYW2020]. What about employers prohibiting employees from attending mass gatherings, bars, restaurants, or even running errands: "there's no possible way they can do that, right?"

To answer these questions, the very first step is to consider the workplace: is the employer a government entity or a private company? Because dealing with government employers raises constitutional issues, here I'll focus solely on private employers. Most private employees are considered "at-will" employees. The standard description of at-will is that these employees may be fired for a good reason, a bad reason, or no reason at all. There are exceptions, of course, especially that employees may not be fired for a discriminatory reason. E.g., [42 U.S.C. $\S$ 2000e-2(a)](https://www.govinfo.gov/content/pkg/USCODE-2018-title42/html/USCODE-2018-title42-chap21-subchapVI-sec2000e-2.htm). Moreover, if an employee has a contract providing for job security, is part of a collective bargaining agreement, or if the employer has somehow agreed to other terms (such as through an employee handbook), then the employer may be less able to require or prohibit the actions discussed below. But most employees in the U.S. lack contract-based job security and are instead at-will.

With these private-sector at-will employees in mind, we turn to the "can they do that?" question. When answering that question it is better to ask if "there anything preventing the employer from doing that?" rather than whether an employer is allowed to take certain actions. To determine if any restrictions on employers exist, one needs to consider federal, state, and local laws. In general, no federal laws clearly prohibit an employer from taking any of these actions as long as they are not enforced in a discriminatory fashion.

## How You Get to Work

Employers may be concerned that employees who make use of public transportation are more at risk of contracting COVID-19 and therefore, at risk of spreading the virus to other employees or customers and clients [@Goldblum2020]. Further, there is an emerging discussion as to whether failing to prohibit such actions by employees would violate the Occupational Safety and Health Act's requirement that employers provide their employees a workplace free from "recognized hazards that are causing or likely to cause death or serious physical harm." [29 U.S.C. $\S$ 654(a)(1)](https://www.govinfo.gov/content/pkg/USCODE-2018-title29/html/USCODE-2018-title29-chap15-sec654.htm). An employer may prohibit an employee from taking public transportation [@Feintzeig2020] unless there is a state law that prohibits such a rule by protecting "lawful conduct" that occurs during non-work hours and off the employer's premises [@Nagele-Piazza2017]. E.g., [California Labor Code $\S$ 96(k)](https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=96); [Colorado Rev. Stat. $\S$ 24-34-402.5(1)](https://casetext.com/statute/colorado-revised-statutes/title-24-government-state/principal-departments/article-34-department-of-regulatory-agencies/part-4-employment-practices/section-24-34-4025-unlawful-prohibition-of-legal-activities-as-a-condition-of-employment); [New York Labor Code $\S$ 201-d(2)(c)](https://www.nysenate.gov/legislation/laws/LAB/201-D); [North Dakota Century Code $\S$ 14-02.4-03(1)](https://www.legis.nd.gov/cencode/t14c02-4.pdf). In other words, where laws like these apply, an employer may not take action against an employee for the employee's lawful conduct outside of the workplace. 

Taking public transportation would be certainly be considered lawful conduct. This raises a number of issues, of course. What counts as public transportation? [@Schauer2008]. Presumably buses, trains, ferries are all public transportation. What about taxis? Or Uber or Lyft? Employers would be well-advised to state clear rules as to what modes of transportation they prohibit or what employees should do if they are required to go to work but public authorities have recommended against the use of public transportation.

In addition, requiring employees to avoid public transportation forces them to drive their own cars and pay for parking (in addition to gas and tolls) or to pay for taxis or Uber/Lyft type transportation (if allowed). Such a requirement raises issues of income disparity. For the most part, income level is not a protected class under federal and state employment discrimination laws. However, a requirement to avoid public transportation might be subject to disparate-impact attack. When an employer has a facially neutral requirement which has disproportionate impact on a protected class, that requirement (here, the prohibition on public transportation) may be a violation unless the employer is able to prove that the prohibition against taking public transportation is "job related" and a "business necessity." [42 U.S.C. $\S$ 2000e-2(k)(1)](https://www.govinfo.gov/content/pkg/USCODE-2018-title42/html/USCODE-2018-title42-chap21-subchapVI-sec2000e-2.htm). Any employee seeking to challenge this requirement would be required to show that a group protected under the employment discrimination statutes (race, color, religion, national origin, sex, or age) is suffering the disproportionate impact.

## Personal Travel

In early 2020, employers responded to the pandemic by canceling non-essential work related travel, then all business travel. Then, for reasons similar to the public transportation ban, some employers began to ask employees to cancel their personal, off-duty travel plans. In other words, the Spring Break trips to Disney were on the chopping block. 

Absent a collective bargaining agreement, provision in an employee handbook, or terms in an individual contract, there is no "entitlement" to vacation time. Therefore, an employer may cancel an employee's vacation. However, if vacation isn't canceled, may the employer prohibit its employees from traveling out-of-state for personal reasons? Some legal commentators have gone so far as to suggest that employers should restrict personal, non-work related travel out of concern for the "needs of the business" in extraordinary times [@Erwin2020]. Still others have stated that employers may not restrict how employees spend their personal time, such as travel [@Feintzeig2020]. Although no reasons are given for this statement, presumably there are two bases for this stance. First, the state laws discussed above (lawful conduct cannot be the basis for an employer's action) and the Americans with Disabilities Act [@Gigante2020]. Therefore, still other legal experts urge employers to tread more carefully in this area. If the employer's main concern is that the employee will become infected or will place other employees at risk of becoming infected, employers should consider the implications of the Americans with Disabilities Act (ADA), [42 U.S.C. $\S$ 12102(1)](https://www.govinfo.gov/content/pkg/USCODE-2018-title42/html/USCODE-2018-title42-chap126-sec12102.htm), and other state or local laws.

The Equal Employment Opportunity Commission -- the federal agency that enforces the ADA --  has not yet opined as to whether an individual who tests positive for COVID-19 falls within the class protected by that statute. Given the ADA's emphasis on individual assessments, not everyone who is or has been infected with COVID-19 will thereby have an "impairment that substantially limits one or more major life activities." [42 U.S.C. $\S$ 12102(1)(A)](https://www.govinfo.gov/content/pkg/USCODE-2018-title42/html/USCODE-2018-title42-chap126-sec12102.htm). For many people, there will be no long term impact from the virus and therefore, COVID-19 infection does not count as a "disability." However, some individuals who are infected may face long-term consequences to their heart and/or lungs [@CDCltecovid]. These "long-haulers" may be significantly limited and therefore fall within the protected class. Further, most federal courts which have considered the issue have held that the ADA does not apply when the employer acts on the basis of the future potential to become disabled. [Shell v. Burlington Northern, 941 F.3d 331 (7th Cir. 2019)](https://casetext.com/case/shell-v-burlington-n-santa-fe-ry-co-3); [EEOC v. STME, LLC, 983 F.3d 1305 (11th Cir. 2019)](https://www.leagle.com/decision/infco20190912060); [Morriss v. BNSF Railway Co., 817 F.3d 1104 (8th Cir. 2016)](https://casetext.com/case/morriss-v-bnsf-ry-co-5); see also [Darby v. Childvine, Inc., 964 F.3d 440, 446 (6th Cir. 2020)](https://www.leagle.com/decision/infco20200630170); [EEOC v. BNSF Railway Co., 902 F.3d 916, 923 (9th Cir. 2018)](https://www.leagle.com/decision/infco20180829137). For example, an employer who restricts an employee from traveling due to concerns over the potential for COVID-19 infection has not violated the ADA because the risk of infection does not make the employee "disabled". However, some localities, such as New York City, consider "actual or perceived infection with COVID-19 to be protected as a disability" [@NYCCHR2020].

Complicating this issue are the number of states that have implemented quarantine requirements after travel to certain states [@Marples2020]. In Pennsylvania, for instance, it is "recommended" that anyone who has traveled to specific states quarantine for 14 days after they return [@PADPH2020a]. In Rhode Island, after arriving from any of the listed states, unless there is proof of a negative test result within the previous 72 hours, the guidance requires that the traveler quarantine for 14 days or face fines [@RIDPH]. These quarantine requirements would keep an employee who traveled to one of the listed states out of the workplace for an additional two weeks. Employers who are not operating remotely therefore have an additional justification (beyond concern for the spread of the virus) for prohibiting employees from traveling out of state. To be clear, in the states with mandatory quarantine requirements, any employee who does travel out of state may not come to the workplace in person during the quarantine period. If the employee did so within the 14 days, they would be engaged in unlawful conduct.

In sum, unless the Americans with Disabilities Act applies or there is a state law (again, as there is in California, Colorado, New York, and North Dakota) prohibiting an employer from doing so, an employer may legally require an employee to avoid off-duty travel out-of-state.

## Activities During Time-Off

Previously uncontroversial activities have taken on new meaning in the age of COVID-19. Frequenting indoor bars and restaurants, attending large gatherings, and engaging in protests all raise concerns for the transmission of the virus. As with the previous categories, the focus should center on whether there is any law prohibiting employers from taking action against employees for these activities. 

Attending large gatherings or frequenting bars could be grounds for dismissal even in states that bar employment retaliation against lawful activities. Many states have limited the number of people who can gather in both outside and inside areas. For example, in Pennsylvania, during the summer, outside events were restricted to no more than 250 people and inside events are limited to no more than 25 people and now are limited by a percentage of capacity [@PADPHorder]. If an employee attended a gathering that violated these restrictions, they would arguably be engaged in unlawful activity and the employer would therefore have grounds to take disciplinary action, even in the minority of states that protect off-duty conduct. Yet, even when an employee violates a COVID-related restriction there can still be uncertainty given courts' mixed messages regarding the legality of these restrictions. Compare [County of Butler v. Wolf, No. 2:20-cv-677, 2020 W.L. 5510690 (W.D. Pa. Sept. 14, 2020)](https://casetext.com/case/cnty-of-butler-v-wolf-1) (striking down restrictions), stay granted by County of Butler v. Governor of Pennsylvania, No. 20-2936, 2020 WL 586893 (3d Cir. Oct. 1, 2020), with [Friends of Danny Devito v. Wolf, 227 A.3d 872 (Pa. 2020)](https://www.clearinghouse.net/chDocs/public/PR-PA-0001-0009.pdf) (upholding restrictions).

Perhaps most surprising to the layperson concerns protests. Many employees believe that any "political" statements are protected as free speech. However, the First Amendment does not apply to private-sector employers. Thus, an employee could be fired for participating in a protest. However, employers should be careful of picking and choosing among the messages of the protests. For example, the two main protests that occurred in the past few months are "Open the State" protests (protesting against stay-at-home and business closure orders) [@Epstein2020] and racial justice protests [@Yang2020]. Given the explicit focus on racial equity and justice in certain protests, employers who chose to discipline employees for engaging in one variety of racial justice protests but not the other could run afoul of Title VII under either an intentional discrimination theory (e.g., "I am going to discipline all those white employees protesting") or a disparate impact discrimination theory (e.g., disciplining employees for a Black Lives Matter protest may result in more Black employees disciplined than white employees).

The bottom line: Employees have significantly less protection than is commonly believed. The question remains as to how an employer might enforce these bans.

## Enforcement and Surveillance

Even when employers may restrict employees' off-duty conduct, questions arise regarding their ability to enforce these new employment requirements. In addition to asking employees to provide statements that they have not violated the prohibitions (and thereby create the potential for termination for false statements to the employer), employers may seek to surveil their employees through monitoring of social media accounts or tracking apps.

A recent study found that approximately half of employers check the social media of their current employees [@Driver2020]. Any public posts that reveal a failure to comply with the employment requirements could prompt, or provide grounds for, the employer to discipline an employee. Moreover, federal law does not prohibit an employer from requesting access to an employee's social media accounts, although many states have recently enacted prohibitions against employers' requiring employees to provide the username and password for their private social media accounts [@WF2020].
	
Enforcing travel or public transportation bans would typically require a tracking app in an employee's smartphone. For many, these apps raise serious privacy concerns. (Ask most teenagers about the invasion of privacy that is Life360, the tracking app that is "ruining their lives" [@Matsakis2020].) Part of the concern centers on protecting the actual data from a breach. However, employees are equally concerned about the collection of the very information. Workplace surveillance is on the rise and has been for years [@Nelson2020]. For surveillance in the workplace itself, employers are able to carry out surveillance as long as they give notice of the surveillance.

It is not as clear whether an employer may engage in surveillance for off-duty behavior. In the time of COVID-19, employers have stronger arguments to monitor off-duty behavior through either tracking apps or, specifically, contract tracing apps. [@Timberg2020]. Employee privacy rights extend to the workplace but these rights are not absolute. If the employer has a legitimate business need (investigating misconduct, for example), then the employee's privacy rights will not prohibit the employer's actions. Tracking off-duty conduct will require an even stronger business need. Protecting the health of employees and customers may be such a need. In addition, for most common law invasion of privacy claims, consent is a defense. E.g., [Lunsford v. Sterilite of Ohio, LLC, No. 2020-Ohio-4193, 2020 WL 5033054 (Ohio, Aug. 26, 2020)](http://www.supremecourt.ohio.gov/rod/docs/pdf/0/2020/2020-Ohio-4193.pdf). In other words, when the employee has consented to the app, she will likely lose on an invasion of privacy claim, absent some sort of duress argument.

Finally, just because an employer can lawfully adopt these restrictions, it doesn't mean that they should. These policies presents risks to morale and workplace cohesion. Employers should proceed carefully and thoughtfully in this area.
